### ISSUE TITLE
好像不会自动更新时间戳

### ISSUE THREAD

**Issue by kaniwow** [Dawnnnnnn/bilibili-live-tools#100]
我昨晚把脚本挂上了服务器，今天好像没有自动签到+领瓜子，不知道是发生了什么

**Comment by DongXiaoChong** [comment]
好像是因为访问拒绝，那个领瓜子领不了

**Comment by Dawnnnnnn** [comment]
签到应该是会签到的，不签到说明在17days之前b站就可能改了点东西。。刚刚更新了，你再测试下吧
