### ISSUE TITLE
为什么在挂机宝上用exe版本,只能检测到某某房间抽奖,却不能领取礼物.而在自己的电脑上可以领取礼物.

### ISSUE THREAD

**Issue by 18395595314** [Dawnnnnnn/bilibili-live-tools#103]
![image](https://user-images.githubusercontent.com/41237775/42726011-1cfbfe3e-87c0-11e8-859e-662df96d7bc5.png)

**Comment by 18395595314** [comment]
是不是云主机上安装的系统缺少什么编译环境或者插件呢

**Comment by Dawnnnnnn** [comment]
你要确认你的vps安装的是正版原装镜像，总是有商家装一个弱智精简版系统，会少很多dll的
