### ISSUE TITLE
Linux下无法运行

### ISSUE THREAD

**Issue by BakaAwt** [Dawnnnnnn/bilibili-live-tools#107]
Python2.7和Python3.6.1均无法运行
原因可能是缺少库文件
详细错误信息如下：
`[root@usla ~]# cd bilibili-live-tools
[root@usla bilibili-live-tools]# python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "/root/bilibili-live-tools/OnlineHeart.py", line 16
    async def apppost_heartbeat(self):
            ^
SyntaxError: invalid syntax
[root@usla bilibili-live-tools]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "/root/bilibili-live-tools/OnlineHeart.py", line 1, in <module>
    from bilibili import bilibili
  File "/root/bilibili-live-tools/bilibili.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[root@usla bilibili-live-tools]# easy_install requests
Searching for requests
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.19.1
Downloading https://files.pythonhosted.org/packages/54/1f/782a5734931ddf2e1494e4cd615a51ff98e1879cbe9eecbdfeaf09aa75e9/requests-2.19.1.tar.gz#sha256=ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a
Processing requests-2.19.1.tar.gz
Running requests-2.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hPwSYI/requests-2.19.1/egg-dist-tmp-SzpfhS
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
warning: no files found matching 'NOTICE'
warning: no files found matching 'requirements.txt'
Adding requests 2.19.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/requests-2.19.1-py2.6.egg
Processing dependencies for requests
Searching for certifi>=2017.4.17
Reading https://pypi.python.org/simple/certifi/
Best match: certifi 2018.4.16
Downloading https://files.pythonhosted.org/packages/4d/9c/46e950a6f4d6b4be571ddcae21e7bc846fcbb88f1de3eff0f6dd0a6be55d/certifi-2018.4.16.tar.gz#sha256=13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7
Processing certifi-2018.4.16.tar.gz
Running certifi-2018.4.16/setup.py -q bdist_egg --dist-dir /tmp/easy_install-32F2gZ/certifi-2018.4.16/egg-dist-tmp-8RQYhM
Adding certifi 2018.04.16 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/certifi-2018.04.16-py2.6.egg
Searching for urllib3>=1.21.1,<1.24
Reading https://pypi.python.org/simple/urllib3/
Best match: urllib3 1.23
Downloading https://files.pythonhosted.org/packages/3c/d2/dc5471622bd200db1cd9319e02e71bc655e9ea27b8e0ce65fc69de0dac15/urllib3-1.23.tar.gz#sha256=a68ac5e15e76e7e5dd2b8f94007233e01effe3e50e8daddf69acfd81cb686baf
Processing urllib3-1.23.tar.gz
Running urllib3-1.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZuAUXT/urllib3-1.23/egg-dist-tmp-9Ou8Ow
warning: no previously-included files matching '*' found under directory 'docs/_build'
zip_safe flag not set; analyzing archive contents...
urllib3.packages.six: module references __path__
Adding urllib3 1.23 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/urllib3-1.23-py2.6.egg
Searching for idna>=2.5,<2.8
Reading https://pypi.python.org/simple/idna/
Best match: idna 2.7
Downloading https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz#sha256=684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16
Processing idna-2.7.tar.gz
Running idna-2.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rtlaVD/idna-2.7/egg-dist-tmp-tzzbWV
warning: no previously-included files matching '*.pyc' found under directory 'tools'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
zip_safe flag not set; analyzing archive contents...
Adding idna 2.7 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/idna-2.7-py2.6.egg
Searching for chardet>=3.0.2,<3.1.0
Reading https://pypi.python.org/simple/chardet/
Best match: chardet 3.0.4
Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz#sha256=84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
Processing chardet-3.0.4.tar.gz
Running chardet-3.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cUBFKU/chardet-3.0.4/egg-dist-tmp-s_L6nC
warning: no files found matching 'requirements.txt'
zip_safe flag not set; analyzing archive contents...
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/bin

Installed /usr/lib/python2.6/site-packages/chardet-3.0.4-py2.6.egg
Finished processing dependencies for requests
[root@usla bilibili-live-tools]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "/root/bilibili-live-tools/OnlineHeart.py", line 1, in <module>
    from bilibili import bilibili
  File "/root/bilibili-live-tools/bilibili.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[root@usla bilibili-live-tools]# 
`

**Comment by Dawnnnnnn** [comment]
你这好像把requests装到python2.6上了吧

用pip3 install requests

**Comment by BakaAwt** [comment]
感谢回复，不过好像还是有问题...
看了一下好像是Unicode无法转换为ASCII的问题
`
[root@usla bilibili-live-tools]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    bilibili()
  File "/root/bilibili-live-tools/bilibili.py", line 31, in __new__
    cls.instance.dic_bilibili = configloader.load_bilibili(file_bilibili)
  File "/root/bilibili-live-tools/configloader.py", line 27, in load_bilibili
    username = input("# \u8f93\u5165\u5e10\u53f7: ")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)
`

**Comment by Dawnnnnnn** [comment]
最上面加个这个吧
# -*- coding: utf-8 -*-
还不行就改服务器的语言设置(好像是这样)
再不行就百度

**Comment by BakaAwt** [comment]
非常感谢！问题已解决！
[root@usla bilibili-live-tools]# -- coding: utf-8   
-bash: --: command not found
[root@usla bilibili-live-tools]# python3 run.py -- coding: utf-8
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    bilibili()
  File "/root/bilibili-live-tools/bilibili.py", line 31, in __new__
    cls.instance.dic_bilibili = configloader.load_bilibili(file_bilibili)
  File "/root/bilibili-live-tools/configloader.py", line 27, in load_bilibili
    username = input("# \u8f93\u5165\u5e10\u53f7: ")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)
[root@usla bilibili-live-tools]# ^C
[root@usla bilibili-live-tools]# export PYTHONIOENCODING=utf-8
[root@usla bilibili-live-tools]# python3 run.py
# 输入帐号: 

是编码的问题，我用export PYTHONIOENCODING=utf-8指令修改了python3的语言设置就能运行了
