### ISSUE TITLE
请教一下输出的信息

### ISSUE THREAD

**Issue by MuGuo** [Dawnnnnnn/bilibili-live-tools#114]
运行过程输出了许多抽奖信息，是这些抽奖被捕捉到的意思吗？

系统公告：最强玩家：只要我开镜，必有蔬菜汁
{'url': 'https://live.bilibili.com/305', 'cmd': 'SYS_MSG', 'msg': '系统公告：最强玩家：只要我开镜，必有蔬菜汁', 'rep': 1}
系统公告：最强玩家：只要我开镜，必有蔬菜汁
{'url': 'https://live.bilibili.com/305', 'cmd': 'SYS_MSG', 'msg': '系统公告：最强玩家：只要我开镜，必有蔬菜汁', 'rep': 1}
系统公告：最强玩家：只要我开镜，必有蔬菜汁
{'msg_text': '若問緣:?送给:?-威尔菌-:?一个摩天大楼，点击前往TA的房间去抽奖吧', 'styleType': 2, 'real_roomid': 333048, 'msg_common': '手游区广播: <%若問緣%>送给<%-威尔菌-%>一个摩天大楼，点击前往TA的房间去抽奖吧', 'msg_self': '手游区广播: <% 若問緣%>送给<%-威尔菌-%>一个摩天大楼，快来抽奖吧', 'rep': 1, 'roomid': 422, 'rnd': 1535175043, 'broadcast_type': 0, 'url': 'http://live.bilibili.com/422', 'cmd': 'SYS_MSG', 'msg': '若問緣:?送给:?-威尔菌-:?一个摩天大楼，点击前往TA的房间去抽 奖吧'}
[2018-08-25 14:00:29] 检测到房间 333048  的广播抽奖
[2018-08-25 14:00:29] 参与了房间 333048  的广播抽奖
[2018-08-25 14:00:29] 广播道具抽奖状态: OK
[2018-08-25 14:00:42] 房间 939654  广播道具抽奖结果: 辣条X1
[2018-08-25 14:01:19] 心跳
[2018-08-25 14:02:43] 房间 333048  广播道具抽奖结果: 辣条X1
{'msg_text': '无非般若皆是妙谛:?送给:?宋快递c:?一个小金人，点击前往TA的房间去抽奖吧', 'styleType': 2, 'real_roomid': 4407336, 'msg_common': '游戏区广播: <%无非般若皆是妙谛%>送给<%宋快递c%>一个小金人，点击前往TA的房间去抽奖吧', 'msg_self': '游戏区广播: <%无非般若皆是妙谛%>送给<%宋快递c%>一个小金人，快来抽奖吧', 'rep': 1, 'roomid': 4407336, 'rnd': 1535176855, 'broadcast_type': 0, 'url': 'http://live.bilibili.com/4407336', 'cmd': 'SYS_MSG', 'msg': '无非般若皆是妙谛:?送给:?宋快递c:?一个小金人，点击前往TA的房间去抽奖吧'}
[2018-08-25 14:03:11] 检测到房间 4407336 的广播抽奖
[2018-08-25 14:03:12] 参与了房间 4407336 的广播抽奖
[2018-08-25 14:03:12] 广播道具抽奖状态: OK
[2018-08-25 14:05:13] 房间 4407336 广播道具抽奖结果: 辣条X1
{'msg_text': '不爱画画的老白:?送给:?小可学妹:?一个小金人，点击前往TA的房间去抽奖吧', 'styleType': 2, 'real_roomid': 6374209, 'msg_common': '娱乐区广播: <%不爱画画的老白%>送给<%小可学妹%>一个小金人，点击前往TA的房间去抽奖吧', 'msg_self': '娱乐区广播: <%不爱画画的老白%>送给<%小可学妹%>一个小金人，快来抽奖吧', 'rep': 1, 'roomid': 605, 'rnd': 8, 'broadcast_type': 0, 'url': 'http://live.bilibili.com/605', 'cmd': 'SYS_MSG', 'msg': '不爱画画的老白:?送给:?小可学妹:?一个小金人，点击前往TA的房间去抽奖吧'}
[2018-08-25 14:05:31] 检测到房间 6374209 的广播抽奖
[2018-08-25 14:05:31] 参与了房间 6374209 的广播抽奖
[2018-08-25 14:05:31] 广播道具抽奖状态: OK

**Comment by Dawnnnnnn** [comment]
啊，这是弹幕原始信息，我调试的时候打开了忘记关了。。。下次版本更新的时候会删掉，不影响使用

**Comment by tt164834887** [comment]
原始信息 另外所有有用的消息应该保存到了log.txt

**Comment by MuGuo** [comment]
明白了，感谢作者

**Comment by YuMu233** [comment]
。。。

在 2018-08-25 14:09:13，Dawnspace <notifications@github.com> 写道：


Closed #114.
