### ISSUE TITLE
建议添加功能

### ISSUE THREAD

**Issue by chenyitian2004** [Dawnnnnnn/bilibili-live-tools#115]
建议添加绘马祈愿功能（入口在直播间输入弹幕的地方的下面），比如隔3天祈愿一次
建议抽到除辣条外的礼物能发个邮件通知（可以让用户自己设置smtp服务器）
建议可以根据时段设置丢弃概率和延迟

**Comment by chenyitian2004** [comment]
还有抽到非辣条礼物邮件通知（用户自设smtp）
谢谢大佬_(:з」∠)_

**Comment by Dawnnnnnn** [comment]
绘马感觉没啥用....通知倒是可以加一个server酱或者smtp,根据时段停止运行这个东西....你添加个windows计划任务吧....没有什么证据表明这个做法能降低进黑屋的几率...

**Comment by chenyitian2004** [comment]
sever酱我用隔壁lzghzr / bilive_client大佬的推送以后不管是安卓模拟器还是手机都会卡死，，，还是smtp吧，，，还有我的挂机宝服务商特别坑，按CPU使用率收费，，能否做个多用户功能。。（或者如果开两个不会增加CPU开销了算了= =）

**Comment by chenyitian2004** [comment]
还有开通舰长的普天同庆和节奏风暴n(*≧▽≦*)n

**Comment by Dawnnnnnn** [comment]
只送当前佩戴的勋章 ，楼上大佬的是多用户版本，CPU使用率倒是没多大影响，如果你用单用户，同时开好几个的话，内存会上升@chenyitian2004

**Comment by chenyitian2004** [comment]
emmmm好吧看来还是我手动送吧。。

**Comment by yjqiang** [comment]
yj的fork版本可以选定主播送勋章……安利 在我github主页有
