### ISSUE TITLE
使用run.zip时候的一个问题

### ISSUE THREAD

**Issue by bilibilibohe** [Dawnnnnnn/bilibili-live-tools#119]
下载了run.zip里面有个exe但是按照双击点开后是一个黑背景一个不停跳的＿，尝试输入帐号才几个数字就出现一闪而过的有文字页面，页面我打算下载ae，然后录制一下看看是什么内容。如果双击后一小段时间就会自动关闭，和朋友说的等待输入帐号密码有所不同

**Comment by bilibilibohe** [comment]
😂学会了另开问题

**Comment by Dawnnnnnn** [comment]
运行环境是什么

**Comment by bilibilibohe** [comment]
我百度了一堆东西后通过cmd输入start 路径后发现再次双击打开那个run.exe后出现了输入账号密码。应该是可以用了，虽然还是很蒙蔽。另外，输入账号密码后他是怎么在线的，和网页登录账号完全不一样

**Comment by Dawnnnnnn** [comment]
都是通过api操作的

**Comment by bilibilibohe** [comment]
![default](https://user-images.githubusercontent.com/42972141/45139881-d2600200-b1e3-11e8-96e2-40ce3f90db28.png)

**Comment by bilibilibohe** [comment]
是这样的话就没有问题了

**Comment by Dawnnnnnn** [comment]
解压出来再用。。

**Comment by bilibilibohe** [comment]
😂解压了解压了
