### ISSUE TITLE
Feature Request:加入剩余可用礼物统计

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#12]
https://api.live.bilibili.com/gift/v2/gift/bag_list
利用这个api，查询剩余礼物，与抽取礼物功能对应。就是不清楚应该写在哪里，是定时显示还是作为查询接口？

**Comment by Dawnnnnnn** [comment]
这个功能用加吗...感觉没啥用

**Comment by yjqiang** [comment]
嗯。。。主要不知道加在哪里？

**Comment by Dawnnnnnn** [comment]
其实随便放在一个里面就行，每隔x秒查询一次

**Comment by yjqiang** [comment]
要不日后作为统一查询接口的一部分？可以后续支持直播经验条等？（flag）

**Comment by Dawnnnnnn** [comment]
图形化会做的(flag)

**Comment by QHDS** [comment]
看到没，这就是dalao.jpg

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/pull/25/commits/ea6fdc5b7545c309f9fad0705542d4a27838c4dc
