### ISSUE TITLE
有人送了十个小电视然后我发现EXE出了问题

### ISSUE THREAD

**Issue by bilibilibohe** [Dawnnnnnn/bilibili-live-tools#120]
<class 'ConnectionAbortedError'> [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
请联系开发者
<class 'ConnectionAbortedError'> [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
请联系开发者

**Comment by bilibilibohe** [comment]
但是回车键按了几下就正常了

**Comment by yjqiang** [comment]
https://stackoverflow.com/questions/17854713/error-errno-10053
Not a bug in python, and we have caught the exception.
