### ISSUE TITLE
如何取消参与电视和高能的抽奖

### ISSUE THREAD

**Issue by ppleonardo** [Dawnnnnnn/bilibili-live-tools#121]
我开了几次脚本就被封了几次，我认为是参与抽奖的次数太多导致的，所以我想关闭掉抽奖功能，只保留上船福利，领瓜子等福利。

**Comment by ppleonardo** [comment]
求求各位大神给支个招，我不求领高能福利，只想要上船福利应该不会被封吧

**Comment by 2314933036** [comment]
取消了是不是什么都不抽了？？

**Comment by 2314933036** [comment]
观看直播的宝箱还是会领的吧？怎么也取消呢？

**Comment by Dawnnnnnn** [comment]
取消了就是什么都不抽了啊，但是别的任务会继续进行，如果想关掉宝箱，应该是在task.py里面

**Comment by ppleonardo** [comment]
求各位大神支个招，怎样有效规避B站直播区的审查，我可以适当放弃脚本部分功能以求稳定，毕竟我只需要养一个勋章，且该勋章已经18级多10万经验，所以不求脚本捡很多辣条，只求稳定。

**Comment by izcbc** [comment]
也反应一下，貌似有上传后，被封时间长了，不知是不是巧合

**Comment by Dawnnnnnn** [comment]
氪金是最有效的方法(′゜ω。‵)

**Comment by ppleonardo** [comment]
我讲讲我自己在B站看直播这一年以来的操作，各位大神不要嘲笑我呀。最开始我氪了一点金，但由于资金有限，我没氪了，改为手动捡辣条了，每天都捡，像上班一样，本来上班都在摸鱼，捡个辣条没多大点事，就是手受不了，太累了。
我学过一段时间计算机，水平就计算机二级的样子吧，然后我自己用按键精灵做了一个脚本，可以实现高能抽奖的功能，是模拟手动进行的，效果还不错，产量虽然比不上这种专业脚本，但不会被封，安全性极高。大家感兴趣的话，我可以贴出来。
后来我觉得诸如其他什么签到、双端登录、应援团、友爱社福利手动领也不费事，就是开宝箱领瓜子挺累的，需要做一个脚本，但是在电脑上需要输入四则运算后的结果，手机上不需要，然后我就在手机上也做了一个按键脚本，专门帮我一键领瓜子，效果挺好的。

**Comment by ppleonardo** [comment]
代码大神勿喷。
我讲讲我自己编的脚本的工作原理，先讲手机领瓜子的吧。
手机包括平板类的设备领瓜子不需要计算什么，所以这给模拟手动进行的脚本创造了使用空间，工作方式就是下载手机版的按键精灵，然后提前录制好点击屏幕的步骤，打开B站随便一个直播间，进入全屏模式后，脚本会按照之前编辑的步骤进行操作，先点击屏幕任意一点，把宝箱图标点出来，然后点击宝箱，它自动就领了，然后再点击确认，这一轮就操作完了，设置一个3分钟的循环，它会自己完成接下来的工作，一个多小时后自己关掉脚本就行了。

**Comment by ppleonardo** [comment]
然后是电脑端模拟手动捡小电视和高能的辣条的脚本，以下是代码，运行环境是按键精灵，开启后需要把画面停留在一个永不下播的直播间（3号）里就行了，这个脚本并不能捡完所有辣条，甚至一个房间超过7个高能都捡不了，也不能领上船福利， 使用的局限性还是很大的，不过该脚本由于其工作原理的关系不会被封禁，安全性是最高的。我就用这个脚本捡了11个月的辣条，把一个勋章养到了18级多10万经验。

**Comment by ppleonardo** [comment]
在按键精灵里是有缩进的，不知道怎么贴在这里就全部对齐了......其工作原理简单来讲就是在留言框里找颜色，把小电视的绿色和高能的绿色（高能以前是粉色）的十六进制代码写进去，然后命令脚本去找这两种颜色，找到了就跳出循环，然后执行点击公告的命令，等待进入抽奖的房间，然后把鼠标移动到点击抽奖的位置，执行多次点击命令，每执行一次点击就可以参与一次抽奖，执行次数可以自己修改，我自己定在了7次，也可以定十几、几十次，但需要考虑的是，在一个房间里待的时间长了会影响到领其他房间辣条的效率，综合考虑定在7次还是比较合理。点击完成后会执行Ctrl w退出该网页的命令，退回到之前永不下播的直播间，清空掉留言框中所有的信息，之所以要清空留言框，是因为脚本是按照从上到下找颜色的顺序进行的，如果不清空，之前领过辣条的房间依然在留言框中，脚本再次执行命令时会进入已参与抽奖的房间，然后不停的循环进入，这样就失去了该有的作用。但这样做也不可避免的会遇到一个问题，就是当多个房间同时在刷高能时，脚本进入第一个房间参与抽奖退出后，清空掉留言框，这样第二个、第三个甚至更多的抽奖房间都无法参与，这就是该脚本捡辣条效率较低的主要原因，所以我尽可能地缩短在抽奖房间里停留的时间，早点出来以便于参加下面房间的抽奖，这也是我把点击抽奖定在7次的主要原因。该脚本运行环境还取决于使用者的电脑性能和网速多少，如何电脑够好，网速够快，脚本执行一次循环的时间在4秒左右，收益能拿到百分之六七十还是不错的。

**Comment by Dawnnnnnn** [comment]
emm，按键精灵相比于这种脚本来说，更像正常人的操作，但不可避免的是内存和cpu的飙升，如果用python调用webdiriver，也能实现相同的效果，或许会降低封号几率。

**Comment by ppleonardo** [comment]
求大神用Python做个类似的，小弟我封号封怕了

**Comment by ppleonardo** [comment]
大神还在吗？十分想要一个基于Python的调用webdriver的脚本

**Comment by ppleonardo** [comment]
我自己做不出来QAQ

**Comment by izcbc** [comment]
怎么关闭上传，晚上11点手动开一次可能被封的慢点，前面被封多久已经忘了。。。或者能输入一个6就操作一次上传的

**Comment by 2314933036** [comment]
exe和py脚本没有实际的差距

**Comment by 18395595314** [comment]
> 用的exe的不太会被封，不参与大航海抽奖，每天下午到晚上12抽高能，应该被封几率会小谁说的

**Comment by 18395595314** [comment]
exe会被封,一样的,小号用exe经常小黑屋

**Comment by yjqiang** [comment]
讨论小黑屋绕过请找到对应issue，不要在不相干的issue下面分开话题

**Comment by louisezhu** [comment]
我昨天被封了哈哈哈哈 所以是新出的上船福利问题还是抽奖的问题啊

**Comment by Dawnnnnnn** [comment]
去另一个issue....
