### ISSUE TITLE
有手机版的吗????

### ISSUE THREAD

**Issue by 18395595314** [Dawnnnnnn/bilibili-live-tools#122]

**Comment by 18395595314** [comment]
手机可以运行py吗

**Comment by zhanzongzhe** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/issues/42

**Comment by 18395595314** [comment]
ok了解

**Comment by ppleonardo** [comment]
有的，需要在手机上装Linux运行环境，不过有点复杂

**Comment by zhanzongzhe** [comment]
复杂什么啊 装个py3 然后两个依赖库就行了

**Comment by 18395595314** [comment]
![a6108ef935910b3183ff0d16168a5c51](https://user-images.githubusercontent.com/41237775/45988196-52251200-c0a8-11e8-878c-f6778c6a8338.jpg)
![d06d6b95b99f8612ff9cf0d920f93363](https://user-images.githubusercontent.com/41237775/45988199-53eed580-c0a8-11e8-80e8-1340ae51659e.jpg)
我已经弄好了,各位大佬

**Comment by zhanzongzhe** [comment]
已解决手机多开

**Comment by zhanzongzhe** [comment]
但是目前看上去还有有问题的

**Comment by VergeDX** [comment]
用 Linux Deploy 吧
@zhanzongzhe
