### ISSUE TITLE
刚才报错了，是b站服务器炸了吗

### ISSUE THREAD

**Issue by lokayimasi** [Dawnnnnnn/bilibili-live-tools#126]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='118.25.108.153', port=8080): Max retries exceeded with url: /guard (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000211D3FF0978>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by Dawnnnnnn** [comment]
有沙雕在ddos我的服务器。。。腾讯云说凌晨恢复
