### ISSUE TITLE
更新后的脚本用不了

### ISSUE THREAD

**Issue by ppleonardo** [Dawnnnnnn/bilibili-live-tools#128]
最近更新的脚本进不去，run和main都不行，直接闪退出来了。想请大神看看怎么回事

**Comment by ppleonardo** [comment]
另外请大神们推荐一下学Python的好教材，好视频什么的，我也想学这个语言，听说是面向对象编程中最简单的，十分感谢大神们

**Comment by Dawnnnnnn** [comment]
在命令行输入 python run.py看看什么报错，估计是没装依赖库

**Comment by Dawnnnnnn** [comment]
视频去b站看啊，b站的教程还是很多的，书就是python核心编程 百度就是廖雪峰

**Comment by ppleonardo** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Python37\bilibili-live-tools-master\requirements.txt

C:\Users\Administrator>C:\Python37\bilibili-live-tools-master\run.py
Traceback (most recent call last):
  File "C:\Python37\bilibili-live-tools-master\run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "C:\Python37\bilibili-live-tools-master\OnlineHeart.py", line 1, in <modu
le>
    from bilibili import bilibili
  File "C:\Python37\bilibili-live-tools-master\bilibili.py", line 12, in <module
>
    from printer import Printer
  File "C:\Python37\bilibili-live-tools-master\printer.py", line 1, in <module>
    from termcolor import *
ModuleNotFoundError: No module named 'termcolor'

C:\Users\Administrator>

**Comment by Dawnnnnnn** [comment]
依赖库没装

pip install termcolor

**Comment by ppleonardo** [comment]
感谢大神，问题解决了，我感到十分的高兴

**Comment by ppleonardo** [comment]
明天之前我就把这个lssue关闭了，在关闭之前还想请教一些问题

**Comment by ppleonardo** [comment]
关于B站监测封号的事，我直到现在还关在小黑屋里呢，B站是怎么针对上我呢？

**Comment by ppleonardo** [comment]
大神可以在未关闭的lssue下作答
