### ISSUE TITLE
反馈一个新问题，这礼物不能自动领取

### ISSUE THREAD

**Issue by englishyj** [Dawnnnnnn/bilibili-live-tools#132]
[Warning]      出现了远古的SYS_GIFT,请尽快联系开发者{'cmd': 'SYS_GIFT', 'msg': '雪昼:? 在直播间 :?562:? 使用了 20 倍节奏风暴，大家快去跟风领取奖励吧！', 'tips': '【雪昼】在直播间【562】使用了 20 倍节奏风暴，大家快去跟风领取奖励吧！', 'msg_text': '【雪昼】在直播间【562】使用了 20 倍节奏风暴，大家快去跟风领取奖励吧！', 'giftId': 39, 'msgTips': 1, 'url': 'http://live.bilibili.com/562', 'roomid': 392351, 'rnd': 1539703431}

**Comment by Dawnnnnnn** [comment]
领20倍节奏风暴的代码在之前的版本中被删除了，具体看wiki的更新日志
