### ISSUE TITLE
新出了高能炮~貌似不能参与抽奖呢

### ISSUE THREAD

**Issue by aileenliu163** [Dawnnnnnn/bilibili-live-tools#134]
还有出现了介个 出现一个未知msg{'cmd': 'ACTIVITY_EVENT', 'data': {'keyword': 'bls_winter_2018', 'type': 'charge', 'limit': 500000, 'progress': 5500}}

**Comment by englishyj** [comment]
加个：     
 elif cmd == "ACTIVITY_EVENT":
            pass

**Comment by Dawnnnnnn** [comment]
高能炮好像是可以的吧。。我记得昨天看过一眼，没啥问题

**Comment by Dawnnnnnn** [comment]
等到一个抽奖，的确是可以参与抽奖的
