### ISSUE TITLE
emmmm

### ISSUE THREAD

**Issue by kaniwow** [Dawnnnnnn/bilibili-live-tools#146]
今天把我的小水管上了18.04TLS，然后发现运行脚本会这样

> Traceback
 (most recent call last):
  File "/root/bili4/OnlineHeart.py", line 87, in run
    await self.guard_lottery()
  File "/root/bili4/OnlineHeart.py", line 35, in guard_lottery
    json_response2 = await response2.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

？

**Comment by Dawnnnnnn** [comment]
下个版本会修，其实不影响运行。。。进小黑屋的账号才会出这个错误提示

**Comment by 18395595314** [comment]
.............................................................

**Comment by yjqiang** [comment]
这里应该是b站问题吧？b站会返回不符合规定的response，明明json格式但是头上标注是其他的，导致aiohttp解析报错

**Comment by Dawnnnnnn** [comment]
是b站的锅。。应该不会出现了
