### ISSUE TITLE
？弹幕那里你在玩蛇么……

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#149]
弹幕那里种类一直都是不断增加的，所以很难穷举。所以我觉得没什么必要审查所有的弹幕种类吧？

**Comment by Dawnnnnnn** [comment]
2333，没事收集下弹幕信息呀，万一有什么新东西还好发现，也能统计一下目前的弹幕种类，对b站的功能模块有个认识
