### ISSUE TITLE
非常高的cpu占用

### ISSUE THREAD

**Issue by out0fmemory** [Dawnnnnnn/bilibili-live-tools#160]
如题，在树莓派3b上，cpu占用直逼单核心100%。。。。。。。

       PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
       1959 pi        20   0  204732  24516   6752 R 100.0  2.7  13:34.33 python3.6

**Comment by yawwwwwn** [comment]
刚才B站大佬们争百强刷爆了，我也是有两分钟逼近CPU100%，然后十多分钟都只检测到不参与抽奖，重启程序也不行。
我估计是response 403了，导致json()失败，于是一直死循环。我已经pull requests了在死循环里加休眠的操作。
403没办法解决，除了换ip，我挂机不参与抽奖的时候手机上试是能抽的。

**Comment by xinxin8816** [comment]
我在路由器上挂，凌晨挂到死机断网了，今天早上一看昨天零点抽了2000多辣条，然后号被封了🙃🙃🙃

**Comment by zhaoqq4** [comment]
已经持续挂了3个月    台式电脑  笔记本  手机  不同切换，还没有进过小黑屋。

**Comment by xinxin8816** [comment]
> 已经持续挂了3个月 台式电脑 笔记本 手机 不同切换，还没有进过小黑屋。

无论在何种设备上挂机，程序都是一样的，效果也是一样的。你不被封应该是另有原因

**Comment by zhaoqq4** [comment]
> > 已经持续挂了3个月 台式电脑 笔记本 手机 不同切换，还没有进过小黑屋。
> 
> 无论在何种设备上挂机，程序都是一样的，效果也是一样的。你不被封应该是另有原因

会不会是 长时间 使用同一个 IP  被封的。

**Comment by Dawnnnnnn** [comment]
下下次更新会留意这个问题

**Comment by yjqiang** [comment]
> 下下次更新会留意这个问题

之前你代码出现过递归问题，我现在看好像没了，你再查查看；以及connect你会如果发生断线，会new object，会不会这里导致的
需要网络部分一个是bilibili.py部分，一个是弹幕了。可以拆开看看具体哪个部分的问题
