### ISSUE TITLE
发现个防止被封号的方法

### ISSUE THREAD

**Issue by englishyj** [Dawnnnnnn/bilibili-live-tools#161]
在领取上船亲密度出错了或者礼物出错的第一次时，退出程序，并且注释掉相关语句，第二天可以避免被封号。

**Comment by yawwwwwn** [comment]
出错具体是指哪种错误

**Comment by yawwwwwn** [comment]
你的意思是被封了马上停止抽奖能减小黑屋的时长是吧，yjqiang的[分支](https://github.com/yjqiang/bilibili-live-tools)好像是实现了小黑屋状态休眠的，你可以去看看。

**Comment by englishyj** [comment]
> 你的意思是被封了马上停止抽奖能减小黑屋的时长是吧，yjqiang的[分支](https://github.com/yjqiang/bilibili-live-tools)好像是实现了小黑屋状态休眠的，你可以去看看。

我是说B站判定应该是看你是否超频抢礼物，超频抢礼物，B站会让你“访问被拒绝”，如果这个时候停止，就可以不进小黑屋，如果继续访问就是真的会进小黑屋，而且领取上船亲密度时候，会经常获取到GuardId=0的信息，要跳过这些，不然也会被封号。

**Comment by englishyj** [comment]
> 那你这个就是薛定谔的猫了。我出现第一次“访问被拒绝”，然后我停止，那这个时候我到底进没进小黑屋呢，只有再抢才能知道吧。哦那你说就停了也不管是不是真的进小黑屋，那我什么时候再开呢？明天是几个小时之后？
> GuardId=0是曙光监控服务器出错了……出来的信息都是不全的，而且时间都是很久之前的了。应该是他清除过期信息的时候的问题吧。不过确实需要规避一下GuardId=0，去领了也是'参数错误'。

但是持续访问被拒绝100%会进小黑屋，提示第一、二次厚立即暂停领取上船亲密度和抢礼物，其他功能不影响，就可以避免被封号。暂停时间的话暂时还说不准，目前感觉应该是6个小时左右。后续再看

**Comment by 2314933036** [comment]
那我到是有个办法,利用校园网晚上会断网的特性就可以避免进黑屋了,还不用去不管他舒服的一批,连续挂了一个月没出事

**Comment by colorsakura** [comment]
使用腾讯云，大会员，月费，风纪委员，一个多月没被封了，昨天有4000多辣条
