### ISSUE TITLE
抽奖变少了？

### ISSUE THREAD

**Issue by samyuan9826** [Dawnnnnnn/bilibili-live-tools#163]
怎么感觉百强之后抽奖变少了？以前日均1000辣条 百强最后一天甚至达到了5000辣条 现在这两天变成了100辣条一天 也没有改过设置
这算是什么原因呢？传说中的小黑屋吗？

**Comment by Dawnnnnnn** [comment]
大佬送的礼物少了就没有辣条了啊。。。小黑屋应该是每天就个位数收入。。目前的版本可能会导致漏监听房间的问题，下个版本修复

**Comment by ppleonardo** [comment]
小黑屋也不止个位数的收入呀，我进过5次以上的小黑屋，进去之后每天也有100多点的辣条，习惯了几个月，现在又放出来了。
