### ISSUE TITLE
自动兑换硬币修改参数就闪退

### ISSUE THREAD

**Issue by ErazerQDY** [Dawnnnnnn/bilibili-live-tools#165]
修改完兑换硬币参数和自动投喂参数之后就闪退，改回来也失效

**Comment by yawwwwwn** [comment]
改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。

**Comment by zhoudengfengderek** [comment]
````
#~~~~
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhoudengfengderek** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ErazerQDY** [comment]
就是0/1这个数值修改之后，脚本会闪退，重新改回原来的数值，依旧如故，只能从压缩包重新解压一份


| |
亚东（常州）科技有限公司 徐俊钰
|
|
邮箱：erazerqdy@163.com
|

签名由 网易邮箱大师 定制

在2018年11月11日 01:02，yawwwwwn 写道：

改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。

**Comment by yawwwwwn** [comment]
> 就是0/1这个数值修改之后，脚本会闪退，重新改回原来的数值，依旧如故，只能从压缩包重新解压一份 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月11日 01:02，yawwwwwn 写道： 改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

哦，我知道了。你不能用记事本改，windows的记事本回车时会在行末写入\r\n，在config里识别不了。你换个文本编辑器比如Notepad++，UltraEdit之类的都行。

**Comment by ErazerQDY** [comment]
はい、ありがとうございます。




| |
亚东（常州）科技有限公司 徐俊钰
|
|
邮箱：erazerqdy@163.com
|

签名由 网易邮箱大师 定制

在2018年11月12日 17:02，yawwwwwn 写道：

就是0/1这个数值修改之后，脚本会闪退，重新改回原来的数值，依旧如故，只能从压缩包重新解压一份 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月11日 01:02，yawwwwwn 写道： 改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

哦，我知道了。你不能用记事本改，windows的记事本回车时会在行末写入\r\n，在config里识别不了。你换个文本编辑器比如Notepad++，UltraEdit之类的都行。

**Comment by yawwwwwn** [comment]
> はい、ありがとうございます。 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月12日 17:02，yawwwwwn 写道： 就是0/1这个数值修改之后，脚本会闪退，重新改回原来的数值，依旧如故，只能从压缩包重新解压一份 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月11日 01:02，yawwwwwn 写道： 改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 哦，我知道了。你不能用记事本改，windows的记事本回车时会在行末写入\r\n，在config里识别不了。你换个文本编辑器比如Notepad++，UltraEdit之类的都行。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

え...对了还有，UltraEdit打开的时候不要点转换到DOS格式。

**Comment by ErazerQDY** [comment]
没问题，好的




| |
亚东（常州）科技有限公司 徐俊钰
|
|
邮箱：erazerqdy@163.com
|

签名由 网易邮箱大师 定制

在2018年11月12日 17:06，yawwwwwn 写道：

はい、ありがとうございます。 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月12日 17:02，yawwwwwn 写道： 就是0/1这个数值修改之后，脚本会闪退，重新改回原来的数值，依旧如故，只能从压缩包重新解压一份 | | 亚东（常州）科技有限公司 徐俊钰 | | 邮箱：erazerqdy@163.com | 签名由 网易邮箱大师 定制 在2018年11月11日 01:02，yawwwwwn 写道： 改回来也失效是什么意思，代码里没写自我修改的操作啊。很好奇。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 哦，我知道了。你不能用记事本改，windows的记事本回车时会在行末写入\r\n，在config里识别不了。你换个文本编辑器比如Notepad++，UltraEdit之类的都行。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

え...对了还有，UltraEdit打开的时候不要点转换到DOS格式。

**Comment by yjqiang** [comment]
操作conf文件建议用vscode或者notepad++

**Comment by englishyj** [comment]
用notepad++编辑，程序猿的日常操作

**Comment by Dawnnnnnn** [comment]
不要用记事本编辑

**Comment by ppleonardo** [comment]
看来有人犯了和我一样的错误，用记事本打开修改，原因是记事本默认ASCII编码解读，其他高级方式可以自动识别配置文件的编码方式，我用pycharm改过去的，大家看到后一定要多留个心呀。
