### ISSUE TITLE
查看今日任务完成情况报错

### ISSUE THREAD

**Issue by KuroZhong** [Dawnnnnnn/bilibili-live-tools#172]
![default](https://user-images.githubusercontent.com/35607238/51075896-c671d880-16cc-11e9-96ae-cee1b71247d9.PNG)

**Comment by yawwwwwn** [comment]
很神奇，我这里按 6 没反应了，错误没出来，最后用 try 捕获到了
`ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/json; charset=utf-8'",)`
content_type 的问题，下次更新会修复。

**Comment by yawwwwwn** [comment]
> #168
> 类似，哈哈，有得改了

我本来是想全给改了的，但是他.json()都是写在各个文件的，都改了还不如重写，那就……能用就行.jpg
