### ISSUE TITLE
如何设置自动送出即将过期的礼物

### ISSUE THREAD

**Issue by ppleonardo** [Dawnnnnnn/bilibili-live-tools#173]
手动送出礼物太麻烦了，如何设置自动送出即将过期的礼物，最好直接清空当天的所有礼物，不存是最好的，谢谢各位大佬。

**Comment by ppleonardo** [comment]
求各位大佬解答，完毕后我立即关闭该问题，不占用大佬的时间。

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/conf/user.conf#L1
详细看wiki，https://github.com/Dawnnnnnn/bilibili-live-tools/wiki#4%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E

**Comment by ppleonardo** [comment]
可是我按照
# 自动送出过期礼物 1代表开启,0代表关闭，send_to_room填入房间号
[gift]
on/off = 1
send_to_room = 558

# 瓜子换硬币
[coin]
on/off = 0

# 将当前佩戴的勋章亲密度送满
[auto-gift]
on/off = 1

# 硬币换瓜子
[doublegain_coin2silver]
on/off = 0
这样设置后，运行run.py直接闪退怎么办

**Comment by ppleonardo** [comment]
我试了很多次了，都是一样的结果，闪退

**Comment by yjqiang** [comment]
那你就等开发者吧  我不参与主分支好久了  读不太懂了

**Comment by Dawnnnnnn** [comment]
拒绝记事本编辑，从现在做起(notepad++)

**Comment by ppleonardo** [comment]
什么是记事本编辑

**Comment by Dawnnnnnn** [comment]
不要用记事本打开修改啊

**Comment by ppleonardo** [comment]
直接在代码上修改吗？

**Comment by ppleonardo** [comment]
原来是我打开的方式不对=。=
我电脑上有pycharm，用它修改了配置文件，秒通过！
谢谢开发者大佬。

**Comment by ppleonardo** [comment]
我查了下问题原因，记事本默认ASCII编码解读，其他高级方式可以自动识别配置文件的编码方式。

**Comment by ppleonardo** [comment]
现在我又有一个新问题，为什么将
当前佩戴的勋章亲密度送满
[auto-gift]
on/off = 1
这里修改为1后，道具包裹里还是会有很多30天的辣条，为什么没有送出去？

**Comment by ppleonardo** [comment]
哦哦，我知道了，刚刚看了过往的问题，发现《提议：自动赠送将过期礼物 #49》和我的问题很像。这个脚本自动送出即将过期的礼物是按天结算的，我打开脚本的一瞬间就已经执行了今天的送出任务，等到明天才会送出下次的，所以这个问题解决了，希望能帮到其他有相同问题的网友，在此还是要感谢一下各位大佬。

**Comment by ppleonardo** [comment]
另外，我还发现《自动兑换硬币修改参数就闪退 #165》这个问题的提出者和我犯了一样的错误，就是用记事本修改配置文件的参数，yawwwwwn大佬给出的解释是不能用记事本改，windows的记事本回车时会在行末写入\r\n，在config里识别不了。换个文本编辑器比如Notepad++，UltraEdit之类的都行。
