### ISSUE TITLE
心跳后就卡住了（可能网络波动问题）

### ISSUE THREAD

**Issue by lyf1134** [Dawnnnnnn/bilibili-live-tools#179]
输3 4  5 6  7 都没有反应
1 2 help 可用
不领辣条和亲密度
只能重启
多次出现

**Comment by yawwwwwn** [comment]
是否cookie过期、登录是否成功。贴一下打开程序后最开始的那一段log。
觉得麻烦就下最新版重新解压输入账号密码运行应该就好了。

**Comment by yjqiang** [comment]
常见的出错原因是cmd里光标，弄进去卡住了程序。

**Comment by lyf1134** [comment]
没有光标
![default](https://user-images.githubusercontent.com/42033610/52534410-21eebf00-2d7c-11e9-8620-bc7eeb622ef6.JPG)

**Comment by yjqiang** [comment]
这个就不太确定了。可能是代码方面问题，但是我不负责这代码很久了 @yawwwwwn 你看看？

**Comment by yjqiang** [comment]
每次都是心跳卡住了么？

**Comment by yawwwwwn** [comment]
完全没有头绪.gif
我这复现不了，曙光说是网络问题，具体等他解释 @Dawnnnnnn 。（不过他说要咕几天。

**Comment by yjqiang** [comment]
> 完全没有头绪.gif
> 我这复现不了，曙光说是网络问题，具体等他解释 @Dawnnnnnn 。（不过他说要咕几天。
> 

你们网络分开了又……出来问题真的头疼

**Comment by lyf1134** [comment]
对，每次都是心跳卡住了
有时候它显示连接舰长失败，但是辣条会继续
有时候就卡死了

**Comment by Dawnnnnnn** [comment]
大概率是网络问题，你是本地挂的吗

**Comment by lyf1134** [comment]
是
问题是它也没有提示
不是有一个“无法连接舰长服务器”
而且过了一会网络应该好了他也不会继续

**Comment by Dawnnnnnn** [comment]
网络问题的确是没有提示的，因为没有设置timeout超时时间，会卡死，就算网络恢复，它还是会卡在上一个请求等待返回包那里，然而网站不会知道你网络什么时候正常，那这个返回包就永远收不到了。建议更换网络或者用服务器挂机

**Comment by lyf1134** [comment]
@yjqiang  我用你的2.0也是经常出现timeout
校园网 是不是和ipv6有关
我ping api.live.bilibili.com 全是ipv6地址

**Comment by yjqiang** [comment]
> @yjqiang 我用你的2.0也是经常出现timeout
> 校园网 是不是和ipv6有关
> 我ping api.live.bilibili.com 全是ipv6地址

timeout正常，就是网络波动，没啥问题。已经处理了。
以及请不要在别人issue里面讨论不想干话题。
我将在30分钟左右删除自己这个comment，希望你也及时删除。

**Comment by yawwwwwn** [comment]
> @yjqiang 我用你的2.0也是经常出现timeout
> 校园网 是不是和ipv6有关
> 我ping api.live.bilibili.com 全是ipv6地址

ping出来的ipv6地址延迟高吗？
那你就ping -4 api.live.bilibili.com比较一下哪个好，ipv4的好你就自己加hosts

**Comment by wanglz111** [comment]
服务器挂机 第一轮lottery结束就卡住了 不知道问题出在何处

**Comment by yawwwwwn** [comment]
> 服务器挂机 第一轮lottery结束就卡住了 不知道问题出在何处

贴具体的log或截图，没看明白

**Comment by lyf1134** [comment]
我把B站的全强制ipv4，就好了

**Comment by kaniwow** [comment]
> 我把B站的全强制ipv4，就好了

难道你直接改hosts？

**Comment by yjqiang** [comment]
@yawwwwwn @Dawnnnnnn 我考虑把这个issue关了。这个issue基本没用了，如果考虑解决网络问题我们另开一个issue专门处理统一的网络模块。

**Comment by 2314933036** [comment]
这个问题我很早就更yj在qq里说过了233

**Comment by yjqiang** [comment]
closed
