### ISSUE TITLE
[疑问] 关于大航海检测

### ISSUE THREAD

**Issue by TheWanderingCoel** [Dawnnnnnn/bilibili-live-tools#180]
那个大佬的航海检测服务器有源码吗,我想在本地搭建一个检测全站上船的服务器。无意冒犯,谢谢了

**Comment by yjqiang** [comment]
没法监控全部的，上船大多数情况下只能本地直播间推送到。只能一个房间一个监控

**Comment by RoninCoel** [comment]
好的,谢谢大佬了。我对这个项目也挺感兴趣的。想请问下这个项目理论上可以不用异步实现吗？

**Comment by yjqiang** [comment]
> 异步实现

aynscio这种很经典的办法。否则你只能多线程之类了。应该不会有更好的办法了

**Comment by RoninCoel** [comment]
谢谢!

**Comment by yawwwwwn** [comment]
> > 好的,谢谢大佬了。我对这个项目也挺感兴趣的。想请问下这个项目理论上可以不用异步实现吗？
> 
> aynscio这种很经典的办法。否则你只能多线程之类了。应该不会有更好的办法了

多线程你得开多少线程。。。一个直播间一个线程吗？

**Comment by yjqiang** [comment]
> > > 好的,谢谢大佬了。我对这个项目也挺感兴趣的。想请问下这个项目理论上可以不用异步实现吗？
> > 
> > aynscio这种很经典的办法。否则你只能多线程之类了。应该不会有更好的办法了
> 
> 多线程你得开多少线程。。。一个直播间一个线程吗？

不用想开线程了，开几十线程就卡得你生活不能自理了。协称开几百毫无压力的

**Comment by yjqiang** [comment]
目前弹幕系统分两种，一个是tcp的，一个是websocket的。这个项目是tcp，我目前比较偏好websocket。tcp的稍微麻烦一点点，不过麻烦不了太多。websocket可能高层一点，占用空间稍微多一点吧，但是我没比较。

**Comment by yjqiang** [comment]
@yawwwwwn Should be closed.

**Comment by Dawnnnnnn** [comment]
没源码，我写的太烂了，还是不放了
