### ISSUE TITLE
求助QAQ：json(content_type=None) 和 勋章查询api返回'data': 'bad token'

### ISSUE THREAD

**Issue by aileenliu163** [Dawnnnnnn/bilibili-live-tools#188]
挂了几个号 就大号出现突然循环出现这个
Traceback (most recent call last):
  File "F:\py\p\OnlineHeart.py", line 114, in run
    json_response = await response.json()
  File "F:\py\lib\site-packages\aiohttp\client_reqrep.py", line 927, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

母鸡啥情况QAQ求助大佬 感谢

**Comment by yawwwwwn** [comment]
在 OnlineHeart.py 的 114 行，`async def run(self):` 中，把
`json_response = await response.json()`
改成
`json_response = await response.json(content_type=None)`

这是B站最近的抽风，下次更新会统一改。

**Comment by lyf1134** [comment]
4
[2019-03-28 14:58:48] [Info]    查询勋章信息
　　　　勋章　　　　 　　　主播昵称　　　     亲密度        今日的亲密度   　　　　排名　　　　  勋章状态
{'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}

**Comment by yawwwwwn** [comment]
> 4
> [2019-03-28 14:58:48] [Info] 查询勋章信息
> 　　　　勋章　　　　 　　　主播昵称　　　 亲密度 今日的亲密度 　　　　排名　　　　 勋章状态
> {'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}

bad token 应该是token信息过期了吧。去 bilibili.conf 中删除 [saved-session] 下每一行等号后的值，记得用非记事本的文本编辑器。或者直接重新解压 bilibili.conf 甚至重新解压整个项目。

Ps. 没啥关联的问题建议另开issue，不要放一起。

**Comment by yawwwwwn** [comment]
> 4
> [2019-03-28 14:58:48] [Info] 查询勋章信息
> 　　　　勋章　　　　 　　　主播昵称　　　 亲密度 今日的亲密度 　　　　排名　　　　 勋章状态
> {'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}

上面的方法别管了。

查了下是有些号最近各种出问题，也没进小黑屋，搞不懂。
bilibili.py 中 215 行，把 [bili_section_post](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/34a38956afdf12df6427a12aa85757e3c50f2eef/bilibili.py#L215) 改成 bili_section_get 就行了。
这一种号只能用 get 方法了，其他的 post 和 get 都行。（上面那些 mimetype 的问题也是这些号出的）

这个查勋章的bug不管也能用，你要查勋章就先自己改吧，曙光说再咕一个月。

**Comment by yjqiang** [comment]
> > 4
> > [2019-03-28 14:58:48] [Info] 查询勋章信息
> > 　　　　勋章　　　　 　　　主播昵称　　　 亲密度 今日的亲密度 　　　　排名　　　　 勋章状态
> > {'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}
> 
> 上面的方法别管了。
> 
> 查了下是有些号最近各种出问题，也没进小黑屋，搞不懂。
> bilibili.py 中 215 行，把 [bili_section_post](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/34a38956afdf12df6427a12aa85757e3c50f2eef/bilibili.py#L215) 改成 bili_section_get 就行了。
> 这一种号只能用 get 方法了，其他的 post 和 get 都行。（上面那些 mimetype 的问题也是这些号出的）
> 
> 这个查勋章的bug不管也能用，你要查勋章就先自己改吧，曙光说再咕一个月。

这个api实际不需要cookie，直接裸着用就行。话说最近经常出这种错误。

**Comment by yawwwwwn** [comment]
> 这个api实际不需要cookie，直接裸着用就行。话说最近经常出这种错误。

`https://api.live.bilibili.com/i/api/medal?page=1&pageSize=50` 这 api 不带 cookie 那查什么玩意

**Comment by yjqiang** [comment]
> > 这个api实际不需要cookie，直接裸着用就行。话说最近经常出这种错误。
> 
> `https://api.live.bilibili.com/i/api/medal?page=1&pageSize=50` 这 api 不带 cookie 那查什么玩意
> 
> 

我看错了  weared那个api不需要

**Comment by masterpiggg** [comment]
我跟楼主有同样的状况，向大佬报告一下：
1. 好一阵子以前开始出现「 [Warning] 出现一个未知msg @[1娱乐分区]1674402 {'cmd': 'ROOM_REAL_TIME_MESSAGE_UPDATE', 'data': {'roomid': 1674402, 'fans': 8937}}」每次数字会不同但是类似这种的，但不影响舰长亲密度领取和高能辣条抽奖。
2. 然后，最近这两三天开始了和楼主一样「Traceback (most recent call last):File "F:\py\p\OnlineHeart.py", line 114, in run json_response = await response.json()」，
3. 心跳频率也变快了的感觉（10秒一次）。
4. 也有执行4勋章讯息不会出来的问题，但我不确定这是什么时候开始的。
5. 大航海上船的亲密度都无法挂机执行领取了（自己手动到直播间还是可以领取），但是高能和小电视的辣条抽奖一切正常，帐号也没被封。
6. 我这情况的时间点是这两三天开始的，有一点不太确定有没有关系，就是我直播年费老爷也是在前几天过期的。
7. 今天我有试了一个小号（从来没挂机过，但也没有氪金过），结果一切正常，包括自动领大航海舰长亲密度和抽辣条，也不会每10秒就心跳，唯一一样的只有第1.项的warning讯息。
8. 有点伤心，希望不是被偷偷限制了吧，虽然挂机说来说去是不对，但是B站直播区我这一年来也氪了将近一个总督钱的礼物，如果刚掉了年费老爷就这样，实在很让人无奈，唉。
9. 最后谢谢大佬提供的exe档，对我这种电脑白痴，也因此受益了无数辣条和亲密度，混得了一两个金牌子，千言万语难以表达感谢！

**Comment by yawwwwwn** [comment]
@masterpiggg 感谢详细反馈
1. 这个 Warning 信息已经处理了，详见[#185](https://github.com/Dawnnnnnn/bilibili-live-tools/pull/185)，代码的最新版已经不会再报了，exe 版还没更。
2. 嗯，就是有的号返回的心跳信息直接 json() 不了，根据上面的方法改一下就行。
3. 因为代码执行遇到错误所以 10s 重试。
4. 查勋章讯息出不来可能之前也由其他原因导致，不记得了，先试试这个 issue 上面说的解决方法。
5. 大航海亲密是在心跳后执行的，心跳一直报错重试就到不了大航海步骤了，解决了心跳问题就成。
6. 氪不改命，没发现这批出问题的号跟是否氪金有关系。
7. 有的号会出本 issue 中提到的一系列问题，而其他号不会。
8. 不知道B站在搞什么幺蛾子。
9. exe 打包频率看曙光心情，但是他代码都懒得更新所以嗯。

**Comment by masterpiggg** [comment]
谢谢ya大佬超仔细的回复，一解心中许多迷惑，感谢！
也小小期待一下大佬们有空的时候更新一下exe版本啦~

**Comment by Dawnnnnnn** [comment]
@yawwwwwn 
exe版本

**Comment by masterpiggg** [comment]
向大佬们报告！！突然正常了！！！（不确定准确时间，应该是这一两个小时内）
心跳恢复了正常，大航海的亲密度也可以自动领取了，虽然不知道为什么，但是恢复了真好。

**Comment by yawwwwwn** [comment]
> 谢谢ya大佬超仔细的回复，一解心中许多迷惑，感谢！
> 也小小期待一下大佬们有空的时候更新一下exe版本啦~

我叫哈欠！
exe 版本已更新 [v4.1](https://github.com/Dawnnnnnn/bilibili-live-tools/releases/tag/4.1)

**Comment by masterpiggg** [comment]
哇神速！谢谢哈欠大佬和曙光大佬！感恩。

**Comment by hierarchsouth** [comment]
exe最新版本不能领上船亲密度

**Comment by yawwwwwn** [comment]
> exe最新版本不能领上船亲密度

啊抱歉我测试的时候注释掉了，现在改过来重新上传了。
