### ISSUE TITLE
希望添加一个本地日志的开关

### ISSUE THREAD

**Issue by luojianxhlxt** [Dawnnnnnn/bilibili-live-tools#189]
看了下目前的配置文件，好像没这个开关
几周过去，程序目录下txt日志有20多M，还是有点多哒

**Comment by yawwwwwn** [comment]
已更新，目前可以选择只对 log.txt 写入 Error 及 Warning 信息，体积应该会小很多。[90f5e26](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/90f5e26d69eff3928e029df9249333ac643cd0af)
