### ISSUE TITLE
推送次数和参与次数相差很大正常么

### ISSUE THREAD

**Issue by slinar** [Dawnnnnnn/bilibili-live-tools#191]
![Snipaste_2019-04-07_22-02-17](https://user-images.githubusercontent.com/41759351/55684728-4ed8e000-5981-11e9-843e-6cdc9fe84540.png)
是有意放弃一些,还是跳过了一些钓鱼的房间

**Comment by yawwwwwn** [comment]
正常。因为同时监控6个分区，那些每个分区都会推送的比如小电视、小金人，只参与一次，所以推送次数多于参与次数。
参与前检测抽奖的直播间，如果被封或被锁会跳过，但这种情况很罕见。
目前没有做那种以为可以减小黑屋概率而故意放弃一定比例的抽奖的机制。

**Comment by yjqiang** [comment]
@yawwwwwn 你打算处理么？处理办法可以截取推送信息，全局还是部分，然后处理。

**Comment by yawwwwwn** [comment]
> @yawwwwwn 你打算处理么？处理办法可以截取推送信息，全局还是部分，然后处理。

我其实是懒得做的。精确这个推送次数没有意义，因为有时候同一房间连着几个高能只会发来一次弹幕信息，然后带 roomid 去获取列表发现是好几个抽奖。通过 msg 切词也太麻烦了……就算切出来也没有一个标准去比较是不是少监控了。所以，算了吧。
