### ISSUE TITLE
运行超载导致电脑重启

### ISSUE THREAD

**Issue by samyuan9826** [Dawnnnnnn/bilibili-live-tools#193]
遇到这个问题大概有20~30次了 平均一个星期一两次 比较好奇有没有好的解决方法。
运行python run.py 几个小时或十几个小时之后，有几率会超载导致电脑直接重启（有时甚至没有空保存其他正在使用的文档233333）我也没有在log之类看到错误提示，曾经测试过电脑只跑python run.py 确定是是因为这个问题

CPU 8th i7
RAM 16GB 
运行方式是vscode的终端里面python run.py （仅占0.1%CPU 和 1% RAM）
python 是Windows 3.7.1 64bit 和 Ubuntu 18.04.1 LTS 里面的python 3 （用了windows subsystem for linux）

没有直接在cmd/powershell/base/wsl 终端里面运行是因为出于某些原因那些终端不会显示中文 只有在vscode里面的终端会显示中文

anyway 刚进大学读编程 所以也不懂是vscode超载还是哪里出错了 比较好奇有木有好的解决方法

新人不懂勿喷Orz

**Comment by Dawnnnnnn** [comment]
那你换个电脑试试呢，我也在本机上运行过十几小时甚至更久，没出现过这种情况

**Comment by wacky6** [comment]
估计是vscode终端渲染的东西内存泄漏了。

我在Docker里面跑好几天也没问题。

**Comment by yawwwwwn** [comment]
我连续运行一周多都不会有炸机的情况，代码里应该也没有不带休眠的死循环了。
为什么不尝试解决“那些终端不会显示中文”的问题呢

**Comment by samyuan9826** [comment]
> 那你换个电脑试试呢，我也在本机上运行过十几小时甚至更久，没出现过这种情况

我大部分情况都没有问题 一般都能跑上一直跑直到这个问题出现 有时候脸好跑了两个星期才出现 昨天跑了两个小时就出现 我换台电脑试试 只是比较好奇哪个环节出了问题

**Comment by samyuan9826** [comment]
> 我连续运行一周多都不会有炸机的情况，代码里应该也没有不带休眠的死循环了。
> 为什么不尝试解决“那些终端不会显示中文”的问题呢

我两台机子都是自带的英文 而且我也把windows 里面language for non-Unicode program 设置成中文了 也不管用 虚拟机跑了unix 也是显示不了中文 所以只能在vscode 里面的终端跑了Orz

**Comment by yjqiang** [comment]
微软cmd默认不是utf8的，导致了utf8显示不全。你安装个pycharm吧，出错了还能看看是咋回事

**Comment by CNOS2499** [comment]
我在服务器上运行了一个月了 也没有导致重启啊
