### ISSUE TITLE
领不了亲密度

### ISSUE THREAD

**Issue by gengjianyue** [Dawnnnnnn/bilibili-live-tools#198]
请问从昨晚开始到现在都领不了奖励是什么情况呀？明明手动有而且可以领

**Comment by gengjianyue** [comment]
好像广播可以，大航海不行

**Comment by wacky6** [comment]
看起来大航海的统计服务器挂了 @Dawnnnnnn

**Comment by yjqiang** [comment]
统计的确是挂了

**Comment by wacky6** [comment]
那个统计服务怎么弄的？有代码/部署包吗？有点想弄个备用服务

**Comment by yawwwwwn** [comment]
> 那个统计服务怎么弄的？有代码/部署包吗？有点想弄个备用服务

[#180](https://github.com/Dawnnnnnn/bilibili-live-tools/issues/180)

**Comment by yawwwwwn** [comment]
> 你舰长服务器真不修了？
> 曙光。 19-05-25 20:32:29
> 修啊
> 曙光。 19-05-25 20:32:33
> 先咕两天

**Comment by yjqiang** [comment]
我这里有项目 https://github.com/yjqiang/YjMonitor @wacky6

**Comment by yawwwwwn** [comment]
已恢复

**Comment by AncientFires** [comment]
舰长服务器一挂，舰队领取率立马从80%降到了50%（同时用的yjqiang大佬的脚本，但只监听了800个房间）

**Comment by yjqiang** [comment]
> 舰长服务器一挂，舰队领取率立马从80%降到了50%（同时用的yjqiang大佬的脚本，但只监听了800个房间）

我的挂4k房间目前挺稳定的，你可以试试扩大房间

**Comment by yjqiang** [comment]
@yawwwwwn 又挂了

**Comment by yawwwwwn** [comment]
目前已稳定，并增加了大乱斗获胜抽奖监控。
