### ISSUE TITLE
bilibili弹幕系统好像升级

### ISSUE THREAD

**Issue by slinar** [Dawnnnnnn/bilibili-live-tools#199]
bilibili弹幕系统好像升级了,会有影响么
https://t.bilibili.com/258961230595770167?tab=2

**Comment by savoki0216** [comment]
我这挂着看抽奖还能抽就是会出现一堆弹幕

**Comment by yawwwwwn** [comment]
看到了，目前不影响，会尽快更新。

**Comment by cjwhkl2008hh** [comment]
目前看已经连接的不成问题，但是无法建立新连接了。新的握手包必须加上key才能收到消息

**Comment by cjwhkl2008hh** [comment]
把连接请求改成
{"uid":0,"roomid":房间号,"protover":2,"platform":"web","clientver":"1.7.3","type":2,"key":令牌}
就行了，令牌就是
https://api.live.bilibili.com/room/v1/Danmu/getConf?room_id=房间号&platform=pc&player=web
返回json里的token

**Comment by wacky6** [comment]
目前没影响。目前看“升级”是在修改发送时的逻辑。

**Comment by yjqiang** [comment]
我觉得只是屏蔽罢了，把弹幕的cmd值稍微一改，就不蹦了。之后会回改的。

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/issues/199#issuecomment-497895658 Confirmed

**Comment by yawwwwwn** [comment]
B站已回改，成功咕到无需更新。XD
