### ISSUE TITLE
一个节奏风暴的小问题

### ISSUE THREAD

**Issue by keyjx3** [Dawnnnnnn/bilibili-live-tools#2]
大佬我也学python我能监控到房间信息但是发送弹幕无法抽奖，你能把代码更新上来或者发我邮箱不 2530449385@qq.com 求一份

**Comment by Dawnnnnnn** [comment]
你试试带上cookie，header，referer..... 而且不用手动发送弹幕啊....不是有join的那个api嘛

**Comment by tt508618** [comment]
请问节奏风暴怎么用的？要要在哪登录？
