### ISSUE TITLE
目前好像没办法领取大航海亲密度

### ISSUE THREAD

**Issue by slinar** [Dawnnnnnn/bilibili-live-tools#203]
试了好几个号都是一样, 应该不是账号的问题, 错误信息如下图
![Snipaste_2019-06-06_22-22-32](https://user-images.githubusercontent.com/41759351/59040618-a0321c80-88a9-11e9-81f8-1bb1296d028c.png)

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/issues/198
