### ISSUE TITLE
程序开启时提示无法登陆

### ISSUE THREAD

**Issue by JerryRich** [Dawnnnnnn/bilibili-live-tools#206]
![TIM图片20190722234551](https://user-images.githubusercontent.com/31468229/61646094-ecf77880-acda-11e9-869d-7a85ed0d337c.png)
持续了好几天了，请问有什么解决方法吗

**Comment by yawwwwwn** [comment]
我刚才测试的最新的commit是正常的。你这个自己找下原因吧：
1. 重新解压从头开始。
2. 账号密码对不对。
3. 是不是因为要输入验证码。目前验证码识别服务器GG，只能等或者改密码。下次更新会给出手动输入验证码的途径。
4. 同设备网页登录看看是否需要手机短信验证。
5. 以上都不是那就往上滑把登录过程部分截图发一下。

**Comment by JerryRich** [comment]
谢谢
