### ISSUE TITLE
新的报错，docker和exe运行都有该问题

### ISSUE THREAD

**Issue by cmydjbf** [Dawnnnnnn/bilibili-live-tools#211]
错误信息
`[2019-08-18 07:01:17] [Error]   登录失败,错误信息为:{'ts': 1566111676, 'code': -2111, 'url': 'https://www.bilibili.com/blackboard/version_upgradetip.html', 'message': '设备验证请升级到最新版本'}`

**Comment by yawwwwwn** [comment]
个人没遇到过。好像是说要去哪个地方关闭一下你的设备登录认证，否则每次在新的设备上登录都要认证。去找一下，看能不能尝试解决。

**Comment by cmydjbf** [comment]
谢谢，按照这个方法已解决
