### ISSUE TITLE
B站最近修改了抽奖方式，礼物需等待1-2分钟才能领奖

### ISSUE THREAD

**Issue by xia1258** [Dawnnnnnn/bilibili-live-tools#215]
脚本绕过了抽奖等待时间，直接参与了抽奖
感觉这可能导致被检测关小黑屋

**Comment by sdfgtre** [comment]
感觉还是看数量吧，领上船亲密度这个功能太猛了，比官方设置的亲密度上限还多，我今天零点多被拒绝访问了

**Comment by xia1258** [comment]
> 感觉还是看数量吧，领上船亲密度这个功能太猛了，比官方设置的亲密度上限还多，我今天零点多被拒绝访问了

我感觉应该是小电视的抱枕抽奖，而不是上船亲密度

**Comment by pjy612** [comment]
App 上面早就是看到奖了要等几分钟，然后在一分钟内领掉。
至于亲密度，带了牌子本身就无上限的，不带牌子就送的是辣条，用辣条去提升亲密度反而有上限。
你要是领取的话 一样是N多辣条 没啥区别。

**Comment by xia1258** [comment]
> App 上面早就是看到奖了要等几分钟，然后在一分钟内领掉。
> 至于亲密度，带了牌子本身就无上限的，不带牌子就送的是辣条，用辣条去提升亲密度反而有上限。
> 你要是领取的话 一样是N多辣条 没啥区别。

之前PC网页端是可以直接抽奖的，现在改版要等时间到才能领了，脚本是直接抽奖

**Comment by LHWsleeve** [comment]
我似乎被小黑屋了...一直被访问被拒绝

**Comment by xia1258** [comment]
> 我似乎被小黑屋了...一直被访问被拒绝

改个密码，第一次小黑屋过个1-2天就好

**Comment by Dawnnnnnn** [comment]
等旧接口完全GG再更新这个(咕

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
