### ISSUE TITLE
点击完exe文件或者运行main.py就显示四行绿字，然后就不执行别的任务了，想知道怎么解决，谢谢了

### ISSUE THREAD

**Issue by lokayimasi** [Dawnnnnnn/bilibili-live-tools#217]
![捕获](https://user-images.githubusercontent.com/32692275/64173688-6c579a80-ce8a-11e9-9cbe-1f9e251cb5d5.PNG)

**Comment by swjturay** [comment]
SSL协议问题
修改bilibili.py的line 40：
            conn=aiohttp.TCPConnector(verify_ssl=False)
            self.bili_session = aiohttp.ClientSession(connector=conn)

**Comment by lokayimasi** [comment]
> SSL协议问题
> 修改bilibili.py的line 40：
> conn=aiohttp.TCPConnector(verify_ssl=False)
> self.bili_session = aiohttp.ClientSession(connector=conn)

解决了，感谢帮助
