### ISSUE TITLE
石油佬百连电视，直接412风控

### ISSUE THREAD

**Issue by ErazerQDY** [Dawnnnnnn/bilibili-live-tools#219]

**Comment by yawwwwwn** [comment]
风控没有办法，毕竟小电视要在两分钟之内抽完（虽然我们还没改，但网页端最新的改版是先等一分钟不让点，再给你一分钟直接领）。
而且是否被风控应该还跟 IP 有权重关系。我自己家宽今晚挂的3个号，都提交了请求，也就是 300 次。其中一个因为在黑屋就全被拒绝，另两个的 100 次抽奖均全部成功获得辣条。

**Comment by Dawnnnnnn** [comment]
可以自己把延迟调高，百连应该还能承受住，除非不是一个号

**Comment by yawwwwwn** [comment]
> 可以自己把延迟调高，百连应该还能承受住，除非不是一个号

具体来说是改[这里](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/8cebb021d9b38e359a10cc236a4349438c8b7046/bilibiliCilent.py#L14)，现在的`await asyncio.sleep(random.uniform(0, min(num, 30)))`是平均分布在 30s 内抽奖，觉得还不行你自己改成 60。
