### ISSUE TITLE
本次参与抽奖结果与实际辣条差很多

### ISSUE THREAD

**Issue by yjsyic** [Dawnnnnnn/bilibili-live-tools#222]
如  输入2  本次参与抽奖结果为2727
     3 实际背包里只有1211

之前这两个数字似乎都是相同的

**Comment by Billyzou0741326** [comment]
房间监听的信息是"SYS_MSG"，这个平时是没问题的，毕竟一直以来小电视/大楼都会同时发布"SYS_MSG"和"NOTICE_MSG"的公告。

但是这次活动的礼物仅触发了"NOTICE_MSG"公告（不在监听范围内），所以bilibiliClient中的parseDanmu方法应该改一下...

**Comment by Billyzou0741326** [comment]
等yawn大佬有空看看吧

**Comment by Dawnnnnnn** [comment]
楼上大佬修了

**Comment by yawwwwwn** [comment]
楼上大佬修的是 #221 ，这个 issue 的问题应该是旧 api 的锅，会尽快更新。

**Comment by yjsyic** [comment]
solved

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
