### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by 715670119** [Dawnnnnnn/bilibili-live-tools#228]
程序很容易卡顿，比如我在家挂机，我人去上夜班了，晚上21点开始，程序就卡顿执行不下去了，有时候晚上在家，21-24点这3小时，需要自己重启很多很多次。建议加个程序自我检测机制，检测到程序不动了，比如获取什么房间，得到了什么，这些都没有滚动更新了，卡住了，此时程序自己重启

**Comment by xia1258** [comment]
> 程序很容易卡顿，比如我在家挂机，我人去上夜班了，晚上21点开始，程序就卡顿执行不下去了，有时候晚上在家，21-24点这3小时，需要自己重启很多很多次。建议加个程序自我检测机制，检测到程序不动了，比如获取什么房间，得到了什么，这些都没有滚动更新了，卡住了，此时程序自己重启

我用的时候不存在卡住的情况，甚至在路由器上都正常跑

**Comment by 715670119** [comment]
应该不是我电脑问题，7代i5跑个python不至于性能不够，白天没有卡顿情况，就晚上21点开始，程序开始卡了，话说今天领取礼物显示访问被拒绝了，不知道为什么，我登陆B站，也没收到封号或者检测到异常的短信，仿佛一切正常，可是软件却不能领取了，手动也显示拒绝访问，我帮别人装了，我拒绝访问的前一天，告诉我他也拒绝访问了

**Comment by xia1258** [comment]
> 应该不是我电脑问题，7代i5跑个python不至于性能不够，白天没有卡顿情况，就晚上21点开始，程序开始卡了，话说今天领取礼物显示访问被拒绝了，不知道为什么，我登陆B站，也没收到封号或者检测到异常的短信，仿佛一切正常，可是软件却不能领取了，手动也显示拒绝访问，我帮别人装了，我拒绝访问的前一天，告诉我他也拒绝访问了

你进小黑屋了，凌晨挂机肯定会黑屋的

**Comment by 715670119** [comment]
应该黑屋2天吧，52破解说的……不过这是另外的问题了，21点开始卡顿依旧不明缘由

**Comment by xia1258** [comment]
黑屋后氪金，解的快一些，不氪金会很久
卡顿尝试放固态试一下

**Comment by yawwwwwn** [comment]
首先我自己本地挂4个号，每天晚上都没问题，偶尔会被风控，但没有卡死的情况。

猜测是晚上高能多的时候协程数过多导致 selector 卡死，这是python的bug，可以关注并更换新版本尝试解决。

检测是否卡住的话，通过协程这边检测我不会。新协程越多只会越容易卡死。通过新线程或新进程检测是否一段时间毫无输出是个思路。再议。

黑屋问题去 #22 讨论。

**Comment by Dawnnnnnn** [comment]
我猜测是你家里的网络问题，换个服务器挂机试试？
