### ISSUE TITLE
question：task类里的Daily_Task是不是实现的双端观看直播并且领奖励呢

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#23]
b站这么搞笑么……连是否满足“每日使用移动端和网页端（双端）分别登录观看任意直播5分钟”都不判断？

**Comment by Dawnnnnnn** [comment]
23333是我懒得写if了，这是之前那个活动时遗留下来的三个API，我看还能做完任务，就没抓新接口，然后执行一遍操作就print ("每日任务完成")，其实我也不知道完成没完成

**Comment by yjqiang** [comment]
那等24h后check吧……看看b站判定方式（好多flag）

**Comment by Dawnnnnnn** [comment]
怕是这个月都完不成了。。。今天还要打比赛，嘤

**Comment by yjqiang** [comment]
那我尽快干掉吧

**Comment by yjqiang** [comment]
{'code': -400, 'msg': '参数错误', 'message': '参数错误', 'data': []}
{'code': -400, 'msg': '奖励尚未完成', 'message': '奖励尚未完成', 'data': []}
{'code': -400, 'msg': '参数错误', 'message': '参数错误', 'data': []}

**Comment by yjqiang** [comment]
{'code': -400, 'msg': '参数错误', 'message': '参数错误', 'data': []}
{'code': 0, 'msg': '', 'message': '', 'data': []}
{'code': -400, 'msg': '参数错误', 'message': '参数错误', 'data': []}

**Comment by yjqiang** [comment]
每日任务就是确认双端观看满5分钟的
但是只有第二个请求管用

**Comment by Dawnnnnnn** [comment]
那删掉就可以了_(:зゝ∠)_
