### ISSUE TITLE
因监控服务器出错导致的舰队亲密度或大乱斗辣条无法领取

### ISSUE THREAD

**Issue by Alkitor** [Dawnnnnnn/bilibili-live-tools#230]
![image](https://user-images.githubusercontent.com/30173062/65774212-62b31100-e170-11e9-88ce-6e2e96cd9182.png)
脚本跑起来的时候，所有亲密度都无法领取，报错已过期，是所有。
![image](https://user-images.githubusercontent.com/30173062/65774313-8ece9200-e170-11e9-80d8-f56c2b843568.png)
执行一段时间之后，心跳只有这么一条info，并不领取亲密度。而且是账号无关的，小号也是同样的问题。另外网页端手动领取没问题。

**Comment by Alkitor** [comment]
哈哈哈，还有有意思的发现，两次运行脚本，报错信息是一样的，也就是房间列表完全一致
![image](https://user-images.githubusercontent.com/30173062/65775356-95f69f80-e172-11e9-8039-444d80a91d7c.png)
![image](https://user-images.githubusercontent.com/30173062/65775453-cc341f00-e172-11e9-989c-0ae677aa2e34.png)
这难道是b站的什么新对策嘛

**Comment by Micah2015** [comment]
commit 9bbcbd6296f0678b8d81e164397fa4f02c8b7d45
2019-09-27 20:17:00 之后就没有上传亲密度领取了

**Comment by Eye522** [comment]
一样不能

**Comment by Eye522** [comment]
每次打开的上船房间都是一样的，不能检测到新房间了

**Comment by xia1258** [comment]
确实，上船亲密度领取不了

**Comment by Eye522** [comment]
B站又更新规则了吧！没关系了，能拣点辣条也不错了

发送自 Windows 10 版邮件应用

发件人: xia
发送时间: 2019年9月28日 22:50
收件人: Dawnnnnnn/bilibili-live-tools
抄送: Eye522; Comment
主题: Re: [Dawnnnnnn/bilibili-live-tools] 亲密度无法领取 (#230)

确实，上船亲密度领取不了

**Comment by yawwwwwn** [comment]
舰队或 PK 多了就容易卡死。欢迎大家在此反馈，但要得曙光睡醒才能修。

**Comment by CYWWY123** [comment]
最近确实上船亲密度领不了 但是辣条很多

**Comment by Billyzou0741326** [comment]
舰长监控服务没法内嵌到软件里 是因为对系统有要求吗

**Comment by xia1258** [comment]
> 舰长监控服务没法内嵌到软件里 是因为对系统有要求吗

更像是避免不必要的麻烦

**Comment by yawwwwwn** [comment]
> 舰长监控服务没法内嵌到软件里 是因为对系统有要求吗

是 python 带不动近万房间的弹幕姬连接。其他的 python 监控都是协同的，本项目用的接口背后是 C# 写的。

**Comment by Billyzou0741326** [comment]
> > 舰长监控服务没法内嵌到软件里 是因为对系统有要求吗
> 
> 是 python 带不动近万房间的弹幕姬连接。其他的 python 监控都是协同的，本项目用的接口背后是 C# 写的。



> > 舰长监控服务没法内嵌到软件里 是因为对系统有要求吗
> 
> 更像是避免不必要的麻烦

了解了  感谢两位大佬

**Comment by xia1258** [comment]
> > 舰长监控服务没法内嵌到软件里 是因为对系统有要求吗
> 
> 是 python 带不动近万房间的弹幕姬连接。其他的 python 监控都是协同的，本项目用的接口背后是 C# 写的。

大乱斗也挂了(一。一;;）

**Comment by Dawnnnnnn** [comment]
我睡醒了，我修好了。

**Comment by CYWWY123** [comment]
> 我睡醒了，我修好了。

大哥牛逼 大哥抽烟

**Comment by xia1258** [comment]
> 我睡醒了，我修好了。

舰队服务器又炸了

**Comment by Dawnnnnnn** [comment]
我这里正常啊

**Comment by CYWWY123** [comment]
> > 我睡醒了，我修好了。
> 
> 舰队服务器又炸了

目前正常 无问题

**Comment by Eye522** [comment]
正常，感谢大哥

**Comment by ErazerQDY** [comment]
大乱斗是不是提前到5点结束了，5点就没看到有大乱斗获胜的推送了

**Comment by yawwwwwn** [comment]
> 大乱斗是不是提前到5点结束了，5点就没看到有大乱斗获胜的推送了

是，17:39最后一个，跟这几天一些群里的消息符合。

**Comment by Eye522** [comment]
舰队监控服务器有办法自己搭建吗？刚才又出问题，感觉好悬

**Comment by CYWWY123** [comment]
> 舰队监控服务器有办法自己搭建吗？刚才又出问题，感觉好悬

我以为是我自己的网络出问题了。。

**Comment by yawwwwwn** [comment]
> 舰队监控服务器有办法自己搭建吗？刚才又出问题，感觉好悬

https://github.com/Dawnnnnnn/bilibili-live-tools/issues/229#issuecomment-536055492

**Comment by like044041** [comment]
大乱斗已经结束好多天了,怎么这里还有显示的,是不是服务器卡了?
![_)COLDO{D @`WPCBMAUNBPT](https://user-images.githubusercontent.com/33434924/66442377-1f5c7a80-ea6d-11e9-86fe-907bd24d30af.png)

**Comment by Eye522** [comment]
在修大乱斗的问题了吗？

**Comment by xia1258** [comment]
> 在修大乱斗的问题了吗？

大乱斗这个并不影响使用

**Comment by QNmay** [comment]
![TIM图片20191013011457](https://user-images.githubusercontent.com/24713552/66705263-ee26c780-ed56-11e9-8e28-1a1da6ffd1f5.png)
今天突然出现这种情况，不知道是什么出了问题，前几天正常使用

**Comment by CYWWY123** [comment]
> ![TIM图片20191013011457](https://user-images.githubusercontent.com/24713552/66705263-ee26c780-ed56-11e9-8e28-1a1da6ffd1f5.png)
> 今天突然出现这种情况，不知道是什么出了问题，前几天正常使用

你号没了

**Comment by Alkitor** [comment]
> ![TIM图片20191013011457](https://user-images.githubusercontent.com/24713552/66705263-ee26c780-ed56-11e9-8e28-1a1da6ffd1f5.png)
> 今天突然出现这种情况，不知道是什么出了问题，前几天正常使用

恭喜初体验，第一次可能有些惊慌，以后就会习以为常了0.0

**Comment by Eye522** [comment]
这个有可能是被封了

**Comment by ErazerQDY** [comment]
> 这个有可能是被封了

就是进了一下小黑屋，没啥大问题，氪点金就出来了

**Comment by Alkitor** [comment]
> > 这个有可能是被封了
> 
> 就是进了一下小黑屋，没啥大问题，氪点金就出来了

可以尝试下找个直播间多发些弹幕，第二天就出来了。至少我最近屡试不爽

**Comment by xia-i** [comment]
> > > 这个有可能是被封了
> > 
> > 
> > 就是进了一下小黑屋，没啥大问题，氪点金就出来了
> 
> 可以尝试下找个直播间多发些弹幕，第二天就出来了。至少我最近屡试不爽

我进去过好几次了，这次好几天了还没出来，氪金都出不来

**Comment by ErazerQDY** [comment]
听说，检测不到大乱斗获胜辣条

**Comment by Alkitor** [comment]
想请教一下，为什么我用docker启动配置文件不能生效。就是user.conf里设置自动送满亲密度，但是并没有送出去

**Comment by paulzzh** [comment]
监控服务器看起来又坏掉了。。

**Comment by WindJ0Y** [comment]
监控服务器目前是什么状态啊，求告知，我这里好像不太好(

**Comment by lovezm** [comment]
我这里提供一个自行搭建的监控服务器 请各位低调使用 不保证啥时候就断更了。
http://api.txsb.vip/jz.php
另外你可能需要修改一下领取流程
我这个接口设置了每40条更新一轮
当然不改也没事啦

**Comment by Alkitor** [comment]
> 我这里提供一个自行搭建的监控服务器 （仅适配https://github.com/Dawnnnnnn/bilibili-live-tools 替换接口直接可用）请各位低调使用 不保证啥时候就断更了。
> http://api.txsb.vip/jz.php
> 另外你可能需要修改一下领取流程
> 我这个接口设置了每40条更新一轮
> 当然不改也没事啦

感谢二狗大佬0.0

**Comment by Billyzou0741326** [comment]
> 我这里提供一个自行搭建的监控服务器 （仅适配https://github.com/Dawnnnnnn/bilibili-live-tools 替换接口直接可用）请各位低调使用 不保证啥时候就断更了。
> http://api.txsb.vip/jz.php
> 另外你可能需要修改一下领取流程
> 我这个接口设置了每40条更新一轮
> 当然不改也没事啦

有现成的那太好了… 我这边就不继续修改了

**Comment by Dawnnnnnn** [comment]
优化，我立刻优化，争取不再GG

**Comment by yawwwwwn** [comment]
曙光说他舰队服务器修好了（确信

**Comment by Billyzou0741326** [comment]
有时间我把这边的推送格式兼容一下 学校的服务器还是比较稳的...
