### ISSUE TITLE
32位不能用

### ISSUE THREAD

**Issue by 3179879706** [Dawnnnnnn/bilibili-live-tools#231]
![360截图20190929205701842](https://user-images.githubusercontent.com/55949138/65832823-c0279900-e2fb-11e9-9d6d-9394f110f312.jpg)

**Comment by CYWWY123** [comment]
exe版32位用不了，要不然用python要不然自己在32位自己打包一份

**Comment by Billyzou0741326** [comment]
用Python运行吧

**Comment by xia1258** [comment]
exe版更新进度不一样即使64位也是不能正常使用的，建议Python

**Comment by yawwwwwn** [comment]
32 位的电脑就装 32 位的 python 环境，pip 32 位的 pyInstaller，然后自己打包，应该就可以了吧。
