### ISSUE TITLE
BUG:一段时间后心跳一次 然后程序卡住无反应

### ISSUE THREAD

**Issue by CYWWY123** [Dawnnnnnn/bilibili-live-tools#232]
时间大约为2小时？暂时不清楚，重启后恢复
![BUG](https://user-images.githubusercontent.com/55469011/65891891-e7539880-e3d7-11e9-81f6-93a292911d33.png)

**Comment by youxiandeyezi** [comment]
我也遇到这个情况了

**Comment by yawwwwwn** [comment]
不知道为什么，exe 版的话刚才打包了最新的，先用最新版的吧。

**Comment by CYWWY123** [comment]
> 不知道为什么，exe 版的话刚才打包了最新的，先用最新版的吧。

我是用python版的自己打包的 我用用最新的exe版试试

**Comment by xia1258** [comment]
python运行没有这个问题，可能exe会出现吧
