### ISSUE TITLE
小BUG：切换监听房间时的偶发性KeyError

### ISSUE THREAD

**Issue by MarcWarrior** [Dawnnnnnn/bilibili-live-tools#233]
![image](https://user-images.githubusercontent.com/33013311/65924337-db3ef980-e41e-11e9-9c91-7522b45f84d3.png)

![image](https://user-images.githubusercontent.com/33013311/65935937-61723480-e44d-11e9-96d6-3344ddec7dbc.png)

**今天早上发现的，在发现监控缺失然后切换房间时会偶发性出现KeyError，如图所示，上面两处切换房间时出现了错误**

**Comment by Billyzou0741326** [comment]
两次错误都来自 21517856 房间  
推测房间号已经从connect.tasks中移除了 但新area和新房间号应该是错位了吧 

105行 `connect.roomids[connect.areas.index(area)]` 获取到的还是旧房间号 所以KeyError...

**Comment by yjqiang** [comment]
。。。弹幕模块逻辑成功把我看自闭了 @yawwwwwn 你来修吧

**Comment by Dawnnnnnn** [comment]
@yawwwwwn 修bug

**Comment by yawwwwwn** [comment]
。。。太偶发了没遇到过。而且我这个用两个list存area跟roomid的方法就只能这样了，要么就得全部重构。先咕咕咕。

**Comment by Dawnnnnnn** [comment]
能用就行.jpg
