### ISSUE TITLE
登录+验证码

### ISSUE THREAD

**Issue by gengjianyue** [Dawnnnnnn/bilibili-live-tools#234]
下了4.3版本，我咋还登录不了。。。明明已经输入账号密码还显示请登录；
还显示个几次“验证码识别服务器连接失败”后，跳出来图片让输入验证码，连续跳出和输入了还多次也没啥反应，是哪里不对了？

**Comment by gengjianyue** [comment]
![image](https://user-images.githubusercontent.com/51013954/66488314-4dc76d80-eae0-11e9-8fcd-c2f21586bf06.png)

**Comment by CYWWY123** [comment]
是不是你自己打开了什么登录验证之类的东西。。。我没有出现这种情况

**Comment by gengjianyue** [comment]
没有呀 用4.2可以正常登陆

**Comment by gengjianyue** [comment]
刚才又试了一下  什么都没动 又可以了
