### ISSUE TITLE
请问，docker版可以增加自动送礼物的功能吗?

### ISSUE THREAD

**Issue by DeSireFire** [Dawnnnnnn/bilibili-live-tools#235]
wiki 上看到了
“ [gift]为自动送到期礼物功能，on/off那里使用 0 和 1 来控制关和开，send_to_room 填入你想要赠送的房间号”
docker版的话，要怎么在命令行传递这个send_to_room参数来达到自动送到期礼物的目的？
如果没有这个功能的话，可以添加一下这个功能吗？
谢谢大佬开发了这么方便的项目。orz

**Comment by MarcWarrior** [comment]
代码里的user.conf应该是只支持自己先写入配置文件的。

configloader.py文件里只有一个load_user()方法，没有write方法。

如果要在命令行传递参数的话，估计可以在biliconsole.py添加这个功能，并且在configloader.py里添加write2user()方法吧。
