### ISSUE TITLE
希望增加定时关闭功能

### ISSUE THREAD

**Issue by xia-i** [Dawnnnnnn/bilibili-live-tools#236]
凌晨挂机容易进黑屋（我每次进黑屋都是凌晨忘记关了，然后下午就进去了）
希望增加可以设置某个时间段不进行任何操作的功能
或者某个时间段才会执行任务的功能

**Comment by CYWWY123** [comment]
> 凌晨挂机容易进黑屋（我每次进黑屋都是凌晨忘记关了，然后下午就进去了）
> 希望增加可以设置某个时间段不进行任何操作的功能
> 或者某个时间段才会执行任务的功能

感觉你可以自己写一个定时自动关机的cmd指令

**Comment by xia-i** [comment]
> > 凌晨挂机容易进黑屋（我每次进黑屋都是凌晨忘记关了，然后下午就进去了）
> > 希望增加可以设置某个时间段不进行任何操作的功能
> > 或者某个时间段才会执行任务的功能
> 
> 感觉你可以自己写一个定时自动关机的cmd指令

我不是挂在服务器上

**Comment by paradox8599** [comment]
加了个简陋的定时开关 [paradox8599/bilibili-live-tools](https://github.com/paradox8599/bilibili-live-tools)
在`main.py`里修改`start_str`和`end_str`自定开关时间
如：
```py
start_str = "08:00"
end_str = "00:00"
```

**Comment by paradox8599** [comment]
加了简陋的定时控制, 自用 [paradox8599/bilibili-live-tools](https://github.com/paradox8599/bilibili-live-tools/blob/master/main.py)

只修改了`main.py`文件

用法：

修改`main.py`里的`START`和`END`来自定开始和结束时间（小时）

`TIME`是检查时间的间隔（分钟）

**Comment by yawwwwwn** [comment]
已更新 [#38a71ca](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/38a71caf3f350753b933268065a5171cddca2209)
