### ISSUE TITLE
辣条提前送掉

### ISSUE THREAD

**Issue by huanghe2015** [Dawnnnnnn/bilibili-live-tools#237]
我现在碰到这个情况：晚上抽的辣条明明是三十天、二十多天的，结果第二天再看就没了。
如果这个普遍存在的话，希望之后改一下逻辑，把辣条当天清掉。
还有，自动送满亲密度可以送多个直播间。望改进（咕咕咕也是常态啦，可以理解）。

**Comment by huanghe2015** [comment]
确认了，第二天会被清掉。欢迎继续观察。

**Comment by yawwwwwn** [comment]
嗯，这里确实没有判断是否即将过期一股脑全送了。下次更新优化一下吧。

**Comment by yawwwwwn** [comment]
之前看错了，如果你用的是 user.conf 里的 [gift] 的话，只会送半天之内过期的礼物。代码逻辑在 [L145](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/34a07f98859a530909431155c8d31936f97346e3/utils.py#L145)。如果确实还不行你艾特一下 Dawnnnnnn 让他再 review 一下。
