### ISSUE TITLE
好像更新了

### ISSUE THREAD

**Issue by kyw97** [Dawnnnnnn/bilibili-live-tools#238]
![RIV3L{~3TWVA64(@U37`~8A](https://user-images.githubusercontent.com/34232137/67848939-98b52d80-fb40-11e9-8546-b95afd5cb568.png)

**Comment by pwq-1313** [comment]
同样问题+1

**Comment by YOYO-beta** [comment]
我也是，是接口变了吗？

**Comment by xia-i** [comment]
是的，接口早就变了，之前只是旧接口还可以用，现在彻底关闭旧接口了

**Comment by CYWWY123** [comment]
不知道后续还会不会更新，男人落泪

**Comment by Mineweeper** [comment]
广播抽奖全黄了，就能领领上舰亲密度了（悲）

**Comment by Eye522** [comment]
舰队亲密修过反而没问题

**Comment by Billyzou0741326** [comment]
要请大佬更新下api端口  而且要等礼物赠送冷却…

**Comment by Billyzou0741326** [comment]
api端口更新没什么问题改下网址就行

但是进行等待的逻辑可能不太好改

**Comment by Eye522** [comment]
知道不好改求也没用

**Comment by Billyzou0741326** [comment]
了解  所以我在想可行的方案…

**Comment by TheWanderingCoel** [comment]
https://api.live.bilibili.com/xlive/lottery-interface/v5/smalltv/join
```
{
"id":"xxxxx",
"roomid":"xxxxx",
"type":"small_tv",
"csrf_token":"xxxx",
"csrf":"xxxx",
"visit_id":""
}
希望有些帮助

**Comment by zhangsmallchi** [comment]
> > https://api.live.bilibili.com/xlive/lottery-interface/v5/smalltv/join
> > ```
> > {
> > "id":"xxxxx",
> > "roomid":"xxxxx",
> > "type":"small_tv",
> > "csrf_token":"xxxx",
> > "csrf":"xxxx",
> > "visit_id":""
> > }
> > 希望有些帮助
> > ```
> 
> 多谢 帮大忙了

不太确定是不是你的方案的问题 用完进小黑屋了。。。

**Comment by Billyzou0741326** [comment]
那我先撤回吧 抱歉…

**Comment by xia-i** [comment]
> 那我先撤回吧 抱歉…

黑屋不是你的问题，单纯只是睡觉时间段/服务器挂封的

**Comment by zhangsmallchi** [comment]
放出日记给你看看吧 我是设定几个特定时间段随机挂机一段时间

> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[3手游分区]92817
> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[4绘画分区]11025535
> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[2网游分区]4966892
> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[6单机分区]1006
> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[1娱乐分区]14617991
> [2019-10-31 08:01:00] [Info]    恭喜主播<%死鬼丶喵%>夺得<%07:00-8:00%>小时总榜第一名！赶快来围观吧~ @[5电台分区]1316958
> [2019-10-31 08:06:02] [Info]    心跳                  
> [2019-10-31 08:06:02] [Error]   连接舰长服务器失败           
> [2019-10-31 08:11:18] [Info]    心跳                  
> [2019-10-31 08:11:18] [Error]   连接舰长服务器失败           
> [2019-10-31 08:16:34] [Info]    心跳                  
> [2019-10-31 08:16:35] [Error]   连接舰长服务器失败           
> [2019-10-31 08:17:42] [Lottery] 检测到房间 6633723 的广播抽奖 @[5电台分区]1316958
> [2019-10-31 08:18:02] [Lottery] 检测到房间 6633723 的广播抽奖 @[5电台分区]1316958
> [2019-10-31 08:18:27] [Lottery] 检测到房间 6633723 的广播抽奖 @[5电台分区]1316958
> [2019-10-31 08:18:46] [Lottery] 参与房间 6633723 广播道具抽奖 459948 状态: 
> [2019-10-31 08:19:04] [Lottery] 参与房间 6633723 广播道具抽奖 459949 状态: 
> [2019-10-31 08:19:26] [Lottery] 参与房间 6633723 广播道具抽奖 459950 状态: 
> [2019-10-31 08:19:57] [Lottery] 房间 6633723 广播道具抽奖 459948 结果: 辣条X1
> [2019-10-31 08:20:27] [Lottery] 房间 6633723 广播道具抽奖 459949 结果: 辣条X1
> [2019-10-31 08:20:28] [Lottery] 房间 6633723 广播道具抽奖 459950 结果: 辣条X1
> [2019-10-31 08:21:50] [Info]    心跳                  
> [2019-10-31 08:21:50] [Error]   连接舰长服务器失败           
> [2019-10-31 12:00:52] [Info]    复用cookie            
> [2019-10-31 12:00:52] [Info]    检查宝箱状态              
> [2019-10-31 12:00:52] [Info]    开始执行每日任务            
> [2019-10-31 12:00:52] [Info]    心跳                  
> [2019-10-31 12:00:52] [Info]    签到状态:今天已签到过         
> [2019-10-31 12:00:52] [Info]    今日宝箱领取完毕            
> [2019-10-31 12:00:53] [Error]   连接舰长服务器失败           
> [2019-10-31 12:00:53] [Lottery] 参与房间 3881807 编号 496283 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:53] [Info]    双端观看直播:奖励已领取        
> [2019-10-31 12:00:53] [Info]    没有将要过期的礼物~          
> [2019-10-31 12:00:53] [Info]    银瓜子兑换硬币状态:每天最多能兑换 1 个
> [2019-10-31 12:00:53] [Lottery] 参与房间 21443732 编号 496284 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:53] [Info]    自动送礼共送出亲密度为0的礼物     
> [2019-10-31 12:00:53] [Lottery] 参与房间 3716898 编号 496285 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:53] [Lottery] 参与房间 498388 编号 496286 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:53] [Lottery] 参与房间 12876195 编号 496314 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:54] [Lottery] 参与房间 21477555 编号 496289 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:54] [Lottery] 参与房间 9751791 编号 496292 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:54] [Info]    [2网游分区] 连接 21461248 弹幕服务器成功
> [2019-10-31 12:00:54] [Lottery] 参与房间 21594151 编号 496334 的大乱斗获胜抽奖: 访问被拒绝
> [2019-10-31 12:00:54] [Info]    [3手游分区] 连接 5248552 弹幕服务器成功
> [2019-10-31 12:00:54] [Info]    [6单机分区] 连接 14032991 弹幕服务器成功
> [2019-10-31 12:00:54] [Info]    [1娱乐分区] 连接 764155 弹幕服务器成功
> [2019-10-31 12:00:54] [Info]    [5电台分区] 连接 927795 弹幕服务器成功
> [2019-10-31 12:00:54] [Info]    [4绘画分区] 连接 5983722 弹幕服务器成功

**Comment by xia-i** [comment]
0-8点=黑屋
服务器(腾讯云 阿里云 百度云等等)挂机=黑屋

**Comment by zhangsmallchi** [comment]
1 我没有从0挂到8点
2 我在家里架了服务器

**Comment by xia-i** [comment]
> 有从0挂到8点
> 2 我在家里架了服务器

那就是你没氪金

**Comment by pang-13** [comment]
氪金免黑屋？

**Comment by xia-i** [comment]
氪金不免黑屋，但是没氪金肯定容易黑屋

**Comment by zhangsmallchi** [comment]
> > 有从0挂到8点
> > 2 我在家里架了服务器
> 
> 那就是你没氪金

我是来讨论的 不是来吵架的朋友 没有证据的话 请您好好说话可好？

**Comment by xia-i** [comment]
> > > 有从0挂到8点
> > > 2 我在家里架了服务器
> > 
> > 
> > 那就是你没氪金
> 
> 我是来讨论的 不是来吵架的朋友 没有证据的话 请您好好说话可好？

我说的是真的啊，没吵架的意思，B站每天关一大批小号，不开脚本都进去

**Comment by Billyzou0741326** [comment]
我看下吧 方案有问题是肯定的 这个确实是我的错

**Comment by kyw97** [comment]
B站现在氪金也会进去，我氪了500该进还是进，认识的几个氪了上万的也在小黑屋关了半个月，我自己开了年费的舰长也在黑屋里，进黑屋主要还是看B站心情，昨天用了楼上大佬的，虽然领的少了点，但是还是可以用的，总比领不到好。

**Comment by Billyzou0741326** [comment]
> > 了解 所以我在想可行的方案…
> 
> 你的方案好像有问题，一段时间后就没有参与抽奖了

忘记加入循环了2333  抽奖次数达到100后任务全部中止了

**Comment by xia-i** [comment]
> B站现在氪金也会进去，我氪了500该进还是进，认识的几个氪了上万的也在小黑屋关了半个月，我自己开了年费的舰长也在黑屋里，进黑屋主要还是看B站心情，昨天用了楼上大佬的，虽然领的少了点，但是还是可以用的，总比领不到好。

氪金多(开过年费大会员/年费姥爷/舰长)的，不在危险时间段和IDC的ip段挂机基本不会进黑屋的
我目前是超过凌晨1点可能进去，超过2点肯定进去，1点前关闭不会进去。

**Comment by xia-i** [comment]
> > > 了解 所以我在想可行的方案…
> > 
> > 
> > 你的方案好像有问题，一段时间后就没有参与抽奖了
> 
> 忘记加入循环了2333 抽奖次数达到100后任务全部中止了

抽奖好像会直接返回信息的，不需要再判断是否中奖

**Comment by Billyzou0741326** [comment]
> > > > 了解 所以我在想可行的方案…
> > > 
> > > 
> > > 你的方案好像有问题，一段时间后就没有参与抽奖了
> > 
> > 
> > 忘记加入循环了2333 抽奖次数达到100后任务全部中止了
> 
> 抽奖会直接返回信息的，不需要判断是否中奖
> {"code":0,"data":{"id":****,"award_id":1,"award_type":0,"award_num":5,"award_image":"[http://i0.hdslb.com/bfs/live/da6656add2b14a93ed9eb55de55d0fd19f0fc7f6.png","award_name":"辣条","award_text":"","award_ex_time":****},"message":"","msg":""}](http://i0.hdslb.com/bfs/live/da6656add2b14a93ed9eb55de55d0fd19f0fc7f6.png%22,%22award_name%22:%22%E8%BE%A3%E6%9D%A1%22,%22award_text%22:%22%22,%22award_ex_time%22:****%7D,%22message%22:%22%22,%22msg%22:%22%22%7D)

抽奖返回值我没留意过多谢指出
判断是否中奖应该是原有的功能吧 我没改那部分

**Comment by Eye522** [comment]
我给你发了个邮件，结果被退回了

发送自 Windows 10 版邮件应用

发件人: kotoriのねこ
发送时间: 2019年10月31日 21:07
收件人: Dawnnnnnn/bilibili-live-tools
抄送: Eye522; Comment
主题: Re: [Dawnnnnnn/bilibili-live-tools] 好像更新了 (#238)

我看下吧 方案有问题是肯定的 这个确实是我的错

**Comment by Billyzou0741326** [comment]
> 我给你发了个邮件，结果被退回了 发送自 Windows 10 版邮件应用 发件人: kotoriのねこ 发送时间: 2019年10月31日 21:07 收件人: Dawnnnnnn/bilibili-live-tools 抄送: Eye522; Comment 主题: Re: [Dawnnnnnn/bilibili-live-tools] 好像更新了 (#238) 我看下吧 方案有问题是肯定的 这个确实是我的错 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Github的邮件提醒是官方提供的 回复邮件提醒是不会发送到我这边的
我邮箱zouguanhan@gmail.com 不介意的话可以再发一遍

**Comment by Eye522** [comment]
看来这个项目完全失效了

**Comment by 2314933036** [comment]
> 0-8点=黑屋
> 服务器(腾讯云 阿里云 百度云等等)挂机=黑屋

我腾讯云挂了1年多了没黑晚上1点到第二天12点暂停脚本

**Comment by Billyzou0741326** [comment]
> > 0-8点=黑屋
> > 服务器(腾讯云 阿里云 百度云等等)挂机=黑屋
> 
> 我腾讯云挂了1年多了没黑晚上1点到第二天12点暂停脚本

如果不是时间段的话... 会是时长的原因吗
我用aws运行的那几次都是一天之内进黑屋而且两个星期才出来....

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
