### ISSUE TITLE
有部分抽奖无法参加

### ISSUE THREAD

**Issue by nita0318** [Dawnnnnnn/bilibili-live-tools#241]
已经是最新版release
日志之一
[Lottery] 参与房间 21467914 广播道具抽奖 460640 状态: 请升级APP版本
{'code': 500, 'data': None, 'message': '请升级APP版本', 'msg': '请升级APP版本'}

**Comment by houxinxin** [comment]
Task exception was never retrieved
future: <Task finished coro=<handle_1_room_TV() done, defined at D:\bilibili-live-tools-master\bilibiliCilent.py:25> exception=KeyError('list')>
Traceback (most recent call last):
  File "D:\bilibili-live-tools-master\bilibiliCilent.py", line 34, in handle_1_room_TV
    checklen = json_response['data']['list']
KeyError: 'list'

现在有这个错误

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
