### ISSUE TITLE
Upgrade Info

### ISSUE THREAD

**Issue by huanghe2015** [Dawnnnnnn/bilibili-live-tools#242]
以下是需要升级的信息：
<“code:500。'data':None,'message':’请升级aPP版本”。'msg'：’请升级aPP版本”>

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
