### ISSUE TITLE
我好像领不了辣条

### ISSUE THREAD

**Issue by henut** [Dawnnnnnn/bilibili-live-tools#244]
能领取上船的亲密度
有检测到广播抽奖，辣条却没有领取
这是什么情况

**Comment by Eye522** [comment]
前段时间要更新APP，更新完不知道哪有问题，就一直是这样

**Comment by Billyzou0741326** [comment]
#240 这个Pull Requests的修改应该解决了辣条领取的问题吧

**Comment by Billyzou0741326** [comment]
顺便提一下… 
用法是下载Pull Request中修改过的文件 覆盖掉相应的原文件 然后正常运行就可以了

**Comment by henut** [comment]
好的谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kotoriのねこ"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 晚上11:22
收件人:&nbsp;"Dawnnnnnn/bilibili-live-tools"<bilibili-live-tools@noreply.github.com&gt;;
抄送:&nbsp;"最繎系坚果丶"<1263067775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Dawnnnnnn/bilibili-live-tools] 我好像领不了辣条 (#244)




顺便提一下…
 用法是下载Pull Request中修改过的文件 覆盖掉相应的原文件 然后正常运行就可以了

**Comment by DeSireFire** [comment]
哇，这个分支还没有合并么。。我说我怎么dokcer pull重拉了，还是没领到辣条。。。

**Comment by Eye522** [comment]
我搞定了，一开始没搞懂

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
