### ISSUE TITLE
新的报错

### ISSUE THREAD

**Issue by lyf1134** [Dawnnnnnn/bilibili-live-tools#245]
[Error]   <class 'OSError'>, [WinError 121] The semaphore timeout period has expired 
 [Warning] 请联系开发者
似乎是网络超时错误

**Comment by yawwwwwn** [comment]
方便把附近的一段log都贴上来吗？

**Comment by lyf1134** [comment]
。。。我已经把文件删了，不过我记得附近比较正常，至少舰队是正常的，
下面好像过一会就会出现XX分区链接失败，然后开始尝试重连，好像一会就又连上了
