### ISSUE TITLE
各位大佬请进

### ISSUE THREAD

**Issue by 715670119** [Dawnnnnnn/bilibili-live-tools#246]
在下小白一枚，求大佬们可否把目前最新的改过的python程序压缩包发我一份，不求exe运行，py就行，正好我学会了py运行这个程序~~

**Comment by pjy612** [comment]
直接去download...

**Comment by 715670119** [comment]
> 直接去download...
code页面的代码没更新啊，我看讨论区好多大佬自己改的，我想求一份

**Comment by Billyzou0741326** [comment]
> > 直接去download...
> > code页面的代码没更新啊，我看讨论区好多大佬自己改的，我想求一份

但是我既不会打包 也不会用pyinstaller...

**Comment by 715670119** [comment]
> > > 直接去download...
> > > code页面的代码没更新啊，我看讨论区好多大佬自己改的，我想求一份
> 
> 但是我既不会打包 也不会用pyinstaller...

emmm就像code页面download的压缩包那样就行了。把本地磁盘解压后的文件夹内的文件，重新变成压缩包就行。

**Comment by Billyzou0741326** [comment]
只压缩源码的话应该没问题 发一下邮箱吧 或者发我一封邮件

**Comment by 715670119** [comment]
> 只压缩源码的话应该没问题 发一下邮箱吧 或者发我一封邮件

715670119@qq.com

**Comment by Billyzou0741326** [comment]
> > 只压缩源码的话应该没问题 发一下邮箱吧 或者发我一封邮件
> 
> [715670119@qq.com](mailto:715670119@qq.com)

发了
