### ISSUE TITLE
开始执行每日任务重复报错

### ISSUE THREAD

**Issue by AnQINNNNN** [Dawnnnnnn/bilibili-live-tools#247]
![D@9 LOD}V%QV0SD{OC%6JE8](https://user-images.githubusercontent.com/54282308/69477683-098bf480-0e24-11ea-9834-64148430bf92.png)
同时广播道具抽奖有提示，但是结算显示错过，不过实际可以收到辣条

**Comment by youxiandeyezi** [comment]
我倒是没报错，不过我只有抽奖信息，没有抽取信息，而且抽奖信息也不全

**Comment by SANSHUISHUI** [comment]
我的和你一样

> 同时广播道具抽奖有提示，但是结算显示错过，不过实际可以收到辣条

我的和你的一样 不晓得为什么这样

**Comment by Billyzou0741326** [comment]
诶 原来旧API可以继续用的吗...

**Comment by Dawnnnnnn** [comment]
签到那个已经被yawwwwwn修好了，抽奖api的全面升级还将由yawwwwwn大佬完成，他说要写完了。

**Comment by yawwwwwn** [comment]
抽奖API已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)
