### ISSUE TITLE
现在是不是亲密度领取不了

### ISSUE THREAD

**Issue by henut** [Dawnnnnnn/bilibili-live-tools#248]
一直领辣条，亲密度领不了？

**Comment by Billyzou0741326** [comment]
> 我这里提供一个自行搭建的监控服务器 （仅适配https://github.com/Dawnnnnnn/bilibili-live-tools 替换接口直接可用）请各位低调使用 不保证啥时候就断更了。
> http://api.txsb.vip/jz.php
> 另外你可能需要修改一下领取流程
> 我这个接口设置了每40条更新一轮
> 当然不改也没事啦

这上面的大佬提供了解决方法
可惜我的监听方式没法照搬过来...

**Comment by zhanzongzhe** [comment]
> > 我这里提供一个自建的监控服务器（仅适用于https://github.com/Dawnnnnnn/bilibili-live-tools替换接口直接可用）请各位低调使用不保证啥时候就断更了。。http 
> > [：// api.txsb.vip/jz.php另外](http://api.txsb.vip/jz.php) 
> > 你可能需要修改一下领取流程
> > 我这个接口设置了每40条更新一轮
> > 当然不改也没事啦
> 
> 这上面的大佬提供了解决方法
> 可惜我的监听方式没法照搬过来...

这个接口要怎么更换呀 大佬

**Comment by Billyzou0741326** [comment]
不太确定... 我没试过

我这边倒是提供舰长+抽奖监听 且覆盖率不低... 
但是推送的方式不怎么兼容 要修改不少逻辑

**Comment by caicaizii** [comment]
替换bilibili.py里guard_list的接口

**Comment by Billyzou0741326** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
这一行就是舰长服务器的接口了

**Comment by ZheJr** [comment]
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
> 
> 
> 这一行就是舰长服务器的接口了

谢谢大佬

**Comment by Billyzou0741326** [comment]
> > https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
> > 
> > 这一行就是舰长服务器的接口了
> 
> 谢谢大佬

其实如果不是楼上的caicaizii大佬提到我还得找半天23333

**Comment by ZheJr** [comment]
> > > https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
> > > 
> > > 这一行就是舰长服务器的接口了
> > 
> > 
> > 谢谢大佬
> 
> 其实如果不是楼上的caicaizii大佬提到我还得找半天23333

我也是OuO

**Comment by ZheJr** [comment]
> > > > https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
> > > > 
> > > > 这一行就是舰长服务器的接口了
> > > 
> > > 
> > > 谢谢大佬
> > 
> > 
> > 其实如果不是楼上的caicaizii大佬提到我还得找半天23333
> 
> 我也是OuO

但我就是找不到

**Comment by Billyzou0741326** [comment]
> 但我就是找不到

还好了... 当时我看了几个星期才看懂怎么连接弹幕的hhh

**Comment by ZheJr** [comment]
> > 但我就是找不到
> 
> 还好了...当时我看了几个星期才看懂怎么连接弹幕的hhh

尝试了一下可以摸小电视了 但是其他的就不知道了

**Comment by Billyzou0741326** [comment]
嗯..... 没报错就是好消息

**Comment by ZheJr** [comment]
> > > 但我就是找不到
> > 
> > 
> > 还好了...当时我看了几个星期才看懂怎么连接弹幕的hhh
> 
> 尝试了一下可以摸小电视了 但是其他的就不知道了

看起来不行啊 现在的情况就是个小电视检测机器 不能自动领

**Comment by Billyzou0741326** [comment]
> 看起来不行啊 现在的情况就是个小电视检测机器 不能自动领

我还以为b站又开放原来的抽奖api 所以关了pull request... 
#240 这个会等到抽奖时间段内再自动参与抽奖

**Comment by ZheJr** [comment]
> > 看起来不行啊 现在的情况就是个小电视检测机器 不能自动领
> 
> 我还以为b站又开放原来的抽奖api 所以关了pull request...
> #240 这个会等到抽奖时间段内再自动参与抽奖

等曙光解决了再说 一晚没睡去补觉

**Comment by Dawnnnnnn** [comment]
明天就修，咕

**Comment by yawwwwwn** [comment]
曙光今天真的修了
