### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by luckysyq** [Dawnnnnnn/bilibili-live-tools#249]
[2019-12-02 07:58:24] [Error]   登录失败,错误信息为:{'code': -449, 'message': '服务繁忙, 请稍后再试', 'ts': 1575273504}
   顺便问下在哪可以修改监听服务器，有大佬可以告知一下吗，源码看了，但是不懂具体改到哪，改出一堆bug

**Comment by yawwwwwn** [comment]
舰长服务器在这 
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
但是你要看看领取部分是否适配。
登录失败是因为好像v2接口改v3了，这两天我们整一下这个项目……

**Comment by Billyzou0741326** [comment]
大佬终于有空了啊233

**Comment by luckysyq** [comment]
> 舰长服务器在这
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/9d1d7960029c6fe6a4169bc4a3ab0b648f195319/bilibili.py#L410
> 
> 
> 但是你要看看领取部分是否适配。
> 登录失败是因为好像v2接口改v3了，这两天我们整一下这个项目……
谢谢

**Comment by Dawnnnnnn** [comment]
v2接口应该要被弃用了，v3接口有geetest不能用，我在tv端找了一个接口，先用着。

**Comment by yawwwwwn** [comment]
已更新 [#a1a7c73](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a1a7c732c9afd13c6eccaa49bba91f9a93a0e0fd)

**Comment by yawwwwwn** [comment]
登录部分已更新 [#a4b521b](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/a4b521b5b3197c4b8234c4e691f04cdb6282093f)

**Comment by luckysyq** [comment]
thank u
