### ISSUE TITLE
连接舰长服务器失败

### ISSUE THREAD

**Issue by Alkitor** [Dawnnnnnn/bilibili-live-tools#251]
运行一段时间就会出现连接服务器失败的错误
![image](https://user-images.githubusercontent.com/30173062/70325329-b62a9500-186c-11ea-8301-c2c52988ab07.png)
![image](https://user-images.githubusercontent.com/30173062/70325345-bd51a300-186c-11ea-933f-60655ad173f1.png)
![image](https://user-images.githubusercontent.com/30173062/70325472-03a70200-186d-11ea-9be4-4a452d067190.png)
![image](https://user-images.githubusercontent.com/30173062/70325497-1588a500-186d-11ea-9eb8-5f3a54b4fb16.png)

**Comment by Alkitor** [comment]
第三张图贴错了，就是40多分的时候还能正常接收，51分出现失败了

**Comment by Alkitor** [comment]
![批注 2019-12-08 002858](https://user-images.githubusercontent.com/30173062/70387533-29551800-19e1-11ea-9416-10c1cc25218c.png)
我打印了一下错误信息是这样的。

**Comment by Alkitor** [comment]
连接失败出现一段时间之后还会恢复，是不是服务器不稳定造成了。
用别的监控服务器没遇到这个问题

**Comment by henut** [comment]
[Error]   连接舰长服务器失败

**Comment by Caimingzhe** [comment]
俺也一样

**Comment by GOOD-AN** [comment]
同。。。

**Comment by Billyzou0741326** [comment]
我这边的fork了自建的服务器... 

修好之前应该可以代替一下

**Comment by Dawnnnnnn** [comment]
修好了
