### ISSUE TITLE
5号命令导致console宕机

### ISSUE THREAD

**Issue by Alkitor** [Dawnnnnnn/bilibili-live-tools#257]
执行5号命令之后，console需要联网查询的功能就不能用了。主程序正常运行。
![批注 2020-01-13 181444](https://user-images.githubusercontent.com/30173062/72248052-33e27d00-3631-11ea-9eca-c823f3a87efb.png)

**Comment by Alkitor** [comment]
另外还有一个问题是新版本之后频繁宕机。主程序宕机，console联网查询的功能不可用但是本地查询正常。之前提过这个事情，但当时没这么频繁，一天大概三四次。新版本之后甚至几分钟程序就死了。

我之前测试发现程序每次停在向监控服务器获取上船列表的时候，不知道是不是什么原因造成了阻塞。另外就是之前监控服务器挂掉，借用别人的监控，期间没有出现过程序宕机的问题，不知道是否跟监控服务器有关。

**Comment by yawwwwwn** [comment]
之前也发现了，`https://api.live.bilibili.com/i/api/liveinfo` 这个 API 有时候会 404，于是卡住循环请求，但是有时候又正常了……再观察几天。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/reqs/utils.py#L131
换这个api可行么

**Comment by MicrosoftKane** [comment]
我也是宕机的厉害，应该是获取舰长奖励的时候卡住的

**Comment by Elu-Thingol** [comment]
或许改成 `https://api.live.bilibili.com/live_user/v1/UserInfo/live_info` 可用

**Comment by witrian** [comment]
我测试了最新的commit，会出现下面两种情况：

![image](https://user-images.githubusercontent.com/9019340/73610196-b9919100-460f-11ea-8570-477a0f7cf4fe.png)

![image](https://user-images.githubusercontent.com/9019340/73610208-d62dc900-460f-11ea-9a1a-398e7e2c5220.png)


改成上面大佬说的

> 或许改成 `https://api.live.bilibili.com/live_user/v1/UserInfo/live_info` 可用

测试了好像可行

**Comment by yawwwwwn** [comment]
已更新。谢谢反馈。
