### ISSUE TITLE
阿里云挂机无效问题，求解

### ISSUE THREAD

**Issue by 0CHaFFeReR0** [Dawnnnnnn/bilibili-live-tools#260]
打算自己用来挂哔哩哔哩辣条的。刚好看到阿里有活动就有想法了。操作系统用的win64位的 。只下载了python3.8.1。环境第三方我也配置好了，在自己的电脑是可以运行并且抢辣条的。但是在服务器里却只有登录进去的状态。没有运行的情况，我操作都是一模一样的。请问这是我少安装了什么吗？大腿们求指点小弟。

**Comment by Sistercon** [comment]
用浏览器进下直播试试  另外不建议用阿里云

**Comment by Billyzou0741326** [comment]
也可以试试别的Python版本

**Comment by Fblackp** [comment]
不建议用云，如果云登录地和你自己所在地一样的话还好。否则很大可能会被弹出访问错误

**Comment by Dawnnnnnn** [comment]
不建议用阿里云，黑屋概率大。你这种情况没有报错的话，我建议你重装系统试试
