### ISSUE TITLE
领取上船奖励的功能失效，不会自动领取（疑似上船监控服务器卡了）

### ISSUE THREAD

**Issue by zazaluMonster** [Dawnnnnnn/bilibili-live-tools#261]
刚开始几天可以正常领取，但是今天发现不会自动领取了， 用的腾讯云，服务器是CentOs的

重启脚本还是没有解决， 想问下是不是常见问题。是的话该如何解决呢

**Comment by zazaluMonster** [comment]
辣条可以正常领取

**Comment by zazaluMonster** [comment]
我自己在浏览器里手动领取上船奖励是可以的

**Comment by zazaluMonster** [comment]
看日志 是2月18号（昨天）下午2点后开始不在领取，重启后日志会刷屏一页领取出错error
```
上船奖励领取出错: {'code': 400, 'data': None, 'message': '已经过期啦,下次早点吧', 'msg': '已经过期啦,下次早点吧'
}
```

**Comment by zazaluMonster** [comment]
是不是对面改了领取机制，导致现有领取算法失效了，希望大大们的关注下。

**Comment by a-writer** [comment]
似乎大佬的监控服务器卡了？手动查看发现最后一个奖励信息为2020-02-18 14:00:02的

**Comment by zazaluMonster** [comment]
> 似乎大佬的监控服务器卡了？手动查看发现最后一个奖励信息为2020-02-18 14:00:02的

是的 我也是这个时间点

**Comment by paradox8599** [comment]
好像是监控服务器出问题了。
过一段时间就会来一次。

**Comment by SenaKawasumi** [comment]
我也一样 突然发现不会涨亲密度了 排查了好久

**Comment by luckyray-fan** [comment]
难怪一打开就刷起一长串过期

**Comment by 666saltedfish** [comment]
应该是接口更新了

**Comment by yawwwwwn** [comment]
接口没更新，这锅曙光背。
Ps. 
![1](https://user-images.githubusercontent.com/40122222/74853282-0ea80380-5381-11ea-8973-19028111bb61.png)

**Comment by Billyzou0741326** [comment]
23333

**Comment by yjqiang** [comment]
新的监控在写，对接了 tcp，但是还在咕。不是我写，我昨晚催了一下。

**Comment by luckyray-fan** [comment]
刚看了下, 似乎能用了

**Comment by zazaluMonster** [comment]
真的谢谢大佬们

**Comment by a-writer** [comment]
那后面更新还会保留http的接口功能吗？昨天临时做了一个http方式的监控备用
