### ISSUE TITLE
弹幕和tcp-monitor模块看的我脑子疼，你不打算重写写？

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#262]
@yawwwwwn 我写了一个danmu-abc的包，你调用就挺方便了，现在这代码真的有点头疼啊。

**Comment by yawwwwwn** [comment]
![敷衍 1](https://user-images.githubusercontent.com/40122222/75150411-a7ef6500-5747-11ea-80db-0287de64fb13.jpg)
有空 1 定

**Comment by Dawnnnnnn** [comment]
下辈子1定
