### ISSUE TITLE
登录的分支问题

### ISSUE THREAD

**Issue by liuyunfz** [Dawnnnnnn/bilibili-live-tools#269]
在错误输入账号后（即返回的错误信息为账号密码输入错误）仍会继续执行线程进行服务器连接与签到任务。

**Comment by liuyunfz** [comment]
虽然在wiki中有提到解决方法，但还是希望能多加一步判断，使用户重新在终端进行输入。

**Comment by Dawnnnnnn** [comment]
能用就行了.jpg

开发者都很懒，尤其是我
