### ISSUE TITLE
增加弹幕服务器的重连机制

### ISSUE THREAD

**Issue by Dawnnnnnn** [Dawnnnnnn/bilibili-live-tools#27]
有用户反馈一段时间后会出现监听不到消息的bug，怀疑是与弹幕服务器的连接断开，重连机制提上日程。

**Comment by Dawnnnnnn** [comment]
基本完成，正在服务器测试。

**Comment by Dawnnnnnn** [comment]
顺便修复了应援团签到失败的bug

**Comment by yjqiang** [comment]
测试好了没有 迫不及待了呀

**Comment by Dawnnnnnn** [comment]
目前还没等到一个流量高峰让我断线。。根本测试不了

**Comment by Dawnnnnnn** [comment]
![](https://i.imgur.com/rSnwcOX.png)
我觉得这大概也许是可以了？11:05到11:20，有抽奖信息吗

**Comment by yjqiang** [comment]
我没挂呢。。。流量高峰在北京时间10点，以及0点左右
