### ISSUE TITLE
5号疑似缺失字段出错

### ISSUE THREAD

**Issue by Elu-Thingol** [Dawnnnnnn/bilibili-live-tools#270]
![图片](https://user-images.githubusercontent.com/22614186/75408632-51557700-5951-11ea-8ca1-b4f91986c706.png)  
看起来好像是返回的数据已经没有 `identification` 字段了，注释此字段后似乎正常执行了  
![图片](https://user-images.githubusercontent.com/22614186/75409021-7991a580-5952-11ea-80db-0bda24ad90cb.png)

**Comment by Billyzou0741326** [comment]
坐标
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/66db5ca5d61bcf8bf5aa47da616277d8a7ddf4a7/utils.py#L88

**Comment by yawwwwwn** [comment]
现在这个 API 返回里又有 "identification" 了啊。CC: @yjqiang 

这个故事告诉我们：只要咕得足够久，bug 就会自己恢复正常。
