### ISSUE TITLE
哪位大佬能分享一下TCP服务器的架设，目标是内网自用

### ISSUE THREAD

**Issue by tlj218** [Dawnnnnnn/bilibili-live-tools#271]
使用了作者开发的代码后，也逐渐的想学习一下TCP服务器的架设，一来是方便自己，二来也是一种兴趣。但是苦于从没有系统的学习过计算机方面的知识，在GitHub里也看了几个关于监控服务器的代码。但是TCP和WS搞不懂区别，也不知道那种搞出来适用于此项目。
就想烦请哪位大佬丢个链接，按照实例来操作一下。

**Comment by Billyzou0741326** [comment]
Python的话可以参考YJ大佬的架构 https://github.com/yjqiang/YjMonitor

**Comment by paradox8599** [comment]
> Python的话可以参考YJ大佬的架构 https://github.com/yjqiang/YjMonitor

我曾经也想自己搭来着，
但是水平有限，
这个项目我实在有点看不懂。
不知道大佬能不能把文档写得更详细些。

**Comment by yjqiang** [comment]
看不懂就对了 ，我也看不懂。。。tcp的server部分打算大改了，不过现在没啥工夫

**Comment by yuban10703** [comment]
> Python的话可以参考YJ大佬的架构 https://github.com/yjqiang/YjMonitor

整了个docker的,能用..好像有问题
yuban10703/yjmonitor

**Comment by yuban10703** [comment]
> > Python的话可以参考YJ大佬的架构 https://github.com/yjqiang/YjMonitor
> 
> 我曾经也想自己搭来着，
> 但是水平有限，
> 这个项目我实在有点看不懂。
> 不知道大佬能不能把文档写得更详细些。
整了个docker的,能用,好像有点问题........
yuban10703/yjmonitor

**Comment by tlj218** [comment]
pi@raspberrypi:~/YjMonitor/server $ sudo python3 run.py
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from db.key_handler import key_handler, KeyCheckVerificationError, KeyCheckMaxError
  File "/home/pi/YjMonitor/server/db/key_handler.py", line 4, in <module>
    from argon2 import PasswordHasher
ImportError: cannot import name 'PasswordHasher' from 'argon2' (/usr/local/lib/python3.7/dist-packages/argon2.py)
这是啥问题，小白看不明白，也百度不出来

**Comment by yuban10703** [comment]
> pi@raspberrypi:~/YjMonitor/server $ sudo python3 run.py
> Traceback (most recent call last):
> File "run.py", line 8, in
> from db.key_handler import key_handler, KeyCheckVerificationError, KeyCheckMaxError
> File "/home/pi/YjMonitor/server/db/key_handler.py", line 4, in
> from argon2 import PasswordHasher
> ImportError: cannot import name 'PasswordHasher' from 'argon2' (/usr/local/lib/python3.7/dist-packages/argon2.py)
> 这是啥问题，小白看不明白，也百度不出来

argon2-cffi这个模块装了么

**Comment by tlj218** [comment]
> > pi @ rasberrypi:~/YJmonitor/server $ sudo py 3 run . py回溯(最后一次调用):文件“run.py”，第8行，in从db.key_handler导入key_handler，KeyCheckVerificationError，KeyCheckMaxError文件"/home/pi/YJMonitor/server/db/key _ handler . py "，第4行，in从argon2导入PasswordHasherImportError:无法从“argon2”导入名称“PasswordHasher”(/usr/local/lib/py 3.7/dist-packages/arg N2 . py)这是啥问题,小白看不明白,也百度不出来
> 
> arg N2-cffi这个模块装了么

安装过了，还是这样报错

**Comment by yuban10703** [comment]
> > > pi @ rasberrypi:~/YJmonitor/server $ sudo py 3 run . py回溯(最后一次调用):文件“run.py”，第8行，in从db.key_handler导入key_handler，KeyCheckVerificationError，KeyCheckMaxError文件"/home/pi/YJMonitor/server/db/key _ handler . py "，第4行，in从argon2导入PasswordHasherImportError:无法从“argon2”导入名称“PasswordHasher”(/usr/local/lib/py 3.7/dist-packages/arg N2 . py)这是啥问题,小白看不明白,也百度不出来
> > 
> > 
> > arg N2-cffi这个模块装了么
> 
> 安装过了，还是这样报错

那就母鸡了,可以看看这个
https://yuban10703.xyz/archives/512

**Comment by tlj218** [comment]
> > > > pi @ rasberrypi:~/YJmonitor/server $ sudo py 3 run . py回溯(最后一次调用):文件“run.py”，第8行，in从db.key_handler导入key_handler，KeyCheckVerificationError，KeyCheckMaxError文件"/home/pi/YJMonitor/server/db/key _ handler . py "，第4行，in从argon2导入PasswordHasherImportError:无法从“argon2”导入名称“PasswordHasher”(/usr/local/lib/py 3.7/dist-packages/arg N2 . py)这是啥问题,小白看不明白,也百度不出来
> > > 
> > > 
> > > arg N2-cffi这个模块装了么
> > 
> > 
> > 安装过了，还是这样报错
> 
> 那就母鸡了,可以看看这个
> https://yuban10703.xyz/archives/512

十分感谢，根据教程已经搞了一遍，就是现在一直报验证码，不知道怎么办，就是账号登录之后monitor部分报验证码，

**Comment by tlj218** [comment]
接楼上，问题解决了，是我路由器设置问题，

**Comment by Dawnnnnnn** [comment]
可以参考 https://github.com/yjqiang/YjMonitor

不过b站这两天改了规则，一个ip最多连接70多个弹幕服务器，架设难度增加了
