### ISSUE TITLE
【Error】报错，海外用户屏蔽未被正确处理

### ISSUE THREAD

**Issue by paradox8599** [Dawnnnnnn/bilibili-live-tools#272]
### 错误内容&重现

用海外VPS（我用的是Vultr日本节点）挂脚本就有几率（？）会出现该错误(前几天就有出现，前天和昨天又正常了，今天又出现了)。运行时无限循环截图中信息，其他功能未受影响。

![original_output](https://user-images.githubusercontent.com/26369746/75596160-8db8dc80-5ae3-11ea-85b1-1e8fe00e5198.png)

### 分析

根据报错判断，是`utils.py`207行收到的json_response未经过验证就对`json_response['data']['uid']`等进行读取，而此时`json_response['data']`为`[]`导致报错。

### 临时方案

暂时在该函数内添加了一个判断，当`code`项不为0（正常返回值）时跳过后面的代码。

```python
# utils.py 第208行
if json_response['code'] != 0:
    Printer().printer(json_response, "Error", "red");
    return
```

![utils_code](https://user-images.githubusercontent.com/26369746/75596485-f3599880-5ae4-11ea-972f-2c688ff41c12.png)

#### 修改后的输出

![output](https://user-images.githubusercontent.com/26369746/75596600-5a774d00-5ae5-11ea-9116-7534e6f09ce9.png)

**Comment by shoucandanghehe** [comment]
我也是海外vps挂的（不知名服务商俄罗斯机子），不过并没有出现这种情况，IP问题？

**Comment by paradox8599** [comment]
> 我也是海外vps挂的（不知名服务商俄罗斯机子），不过并没有出现这种情况，IP问题？

也许是，毕竟Vultr。
我自己也不是每天都有报错，大概是B站抽风。。？
但既然有报错的可能，就提一下了，万一有人一样呢。

**Comment by yawwwwwn** [comment]
不推荐用海外 IP 挂，因为放映厅及音乐台在海外都是不让看的，于是包括领取抽奖之前的检查房间是否被封禁时的 `room_init` 都无法获取到数据。下次更新会在代码上避免报错，但是海外给被屏蔽直播间送礼无法实现。

**Comment by shoucandanghehe** [comment]
> 不推荐用海外 IP 挂，因为放映厅及音乐台在海外都是不让看的，于是包括领取抽奖之前的检查房间是否被封禁时的 `room_init` 都无法获取到数据。下次更新会在代码上避免报错，但是海外给被屏蔽直播间送礼无法实现。

理解理解，不过放映厅和音乐台会送辣条的不多吧233，问题不大

**Comment by Billyzou0741326** [comment]
有的有的 我就大部分送音乐台

**Comment by shoucandanghehe** [comment]
> 有的有的 我就大部分送音乐台

打脸现场（疼）

**Comment by paradox8599** [comment]
> 不推荐用海外 IP 挂，因为放映厅及音乐台在海外都是不让看的，于是包括领取抽奖之前的检查房间是否被封禁时的 `room_init` 都无法获取到数据。下次更新会在代码上避免报错，但是海外给被屏蔽直播间送礼无法实现。

理解理解，我的意思是这个报错可以handle一下。
由于各种原因，我暂时没办法用国内ip挂。
反正我也不需要给这些直播间送礼。😂

**Comment by yawwwwwn** [comment]
已修复 #[7314876](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/731487601e06f8d598d1db03c924b58a87a80491) 。
