### ISSUE TITLE
新更新如果关闭定时休眠功能将一直处于休眠状态   |程序自带监控服务器疑似炸了

### ISSUE THREAD

**Issue by a-writer** [Dawnnnnnn/bilibili-live-tools#273]
程序自带的舰长服务器应该炸了，导致主界面卡死
http://118.25.108.153:8080/pk
http://118.25.108.153:8080/guard

**Comment by a-writer** [comment]
提供一个临时解决方法
在bilibili.py中
约416行http://118.25.108.153:8080/guard
替换为https://cdn.tpdw.ml/api/bili/getGuard
约424行http://118.25.108.153:8080/pk
替换为https://cdn.tpdw.ml/api/bili/getPk
这个是个人使用，可能不是很好用，不是很全...
大佬放过略过

**Comment by Billyzou0741326** [comment]
不错2333

**Comment by Hashida-Itaru-19910519** [comment]
由此推论最近经常莫名卡死可能与舰长服务器有关

**Comment by Billyzou0741326** [comment]
#259 

> @yawwwwwn
> 哈欠大佬
> 我试着自己加 log 找出卡在哪里， 发现好象是在等舰长服务器反馈
> ![image](https://user-images.githubusercontent.com/9019340/75561275-b27c6800-5a81-11ea-907c-67914f5a049e.png)
> 
> ![
image](https://user-images.githubusercontent.com/9019340/75561205-95e03000-5a81-11ea-8382-2f991ee5a7cf.png)

非异步requests默认没有timeout

**Comment by a-writer** [comment]
怪不得我说怎么换了的这两天都不怎么卡233

**Comment by witrian** [comment]
感谢～
我还以为我自己改了那个request timeout 过后 
怎么一直爆Error了 明明早上还跑得好好的

`[Error]   连接舰长服务器失败 `

**Comment by Billyzou0741326** [comment]
服务器无响应就error了嘛

**Comment by witrian** [comment]
> 服务器无响应就error了嘛

是啊，就刚刚有段时间自带的舰长服务器炸了，一直连接失败，
所以用大佬给的链接改了一个双重监听，自带的舰长服务器还是连接失败。。
结果，
发完上面那个comment了过后，
自带的舰长服务器修复了。。。
![image](https://user-images.githubusercontent.com/9019340/75628567-4468aa00-5c15-11ea-9278-ec144f5449b5.png)

**Comment by a-writer** [comment]
自带的恢复了挺好的

**Comment by henut** [comment]
[2020-03-03 22:29:56] [Info]    定时休眠，跳过房间 21585497 编号 2137398 的上船奖励
[2020-03-03 22:29:56] [Info]    定时休眠，跳过房间 14798635 编号 2137842 的上船奖励
-------------------
这个在哪修改

**Comment by a-writer** [comment]
没设置定时休眠的设置个定时休眠就能用了
如果是手动开关的设置不用的时间即可

**Comment by witrian** [comment]
可能是 下面这个改动的锅
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/schedule.py#L23

跑了这个 制成true
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/run.py#L72

然后因为conf 没开定时  所以没跑 schedule.run() 没机会置回false
> schedule = Schedule()
if dic_user['regular_sleep']['on/off'] == "1":
    tasks.append(schedule.run(dic_user['regular_sleep']['schedule']))

目前workaround就是跟楼上说的一样，自己去user.conf 改 L24-25

> 没设置定时休眠的设置个定时休眠就能用了
> 如果是手动开关的设置不用的时间即可

https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/conf/user.conf#L24

**Comment by henut** [comment]
> 可能是 下面这个改动的锅
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/schedule.py#L23
> 
> 跑了这个 制成true
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/run.py#L72
> 
> 然后因为conf 没开定时 所以没跑 schedule.run() 没机会置回false
> 
> > schedule = Schedule()
> > if dic_user['regular_sleep']['on/off'] == "1":
> > tasks.append(schedule.run(dic_user['regular_sleep']['schedule']))
> 
> 目前workaround就是跟楼上说的一样，自己去user.conf 改 L24-25
> 
> > 没设置定时休眠的设置个定时休眠就能用了
> > 如果是手动开关的设置不用的时间即可
> 
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/conf/user.conf#L24


我把这个改回false就可以用了
![Uploading Snipaste_2020-03-03_23-07-49.jpg…]()





> 可能是 下面这个改动的锅
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/schedule.py#L23
> 
> 跑了这个 制成true
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/run.py#L72
> 
> 然后因为conf 没开定时 所以没跑 schedule.run() 没机会置回false
> 
> > schedule = Schedule()
> > if dic_user['regular_sleep']['on/off'] == "1":
> > tasks.append(schedule.run(dic_user['regular_sleep']['schedule']))
> 
> 目前workaround就是跟楼上说的一样，自己去user.conf 改 L24-25
> 
> > 没设置定时休眠的设置个定时休眠就能用了
> > 如果是手动开关的设置不用的时间即可
> 
> https://github.com/Dawnnnnnn/bilibili-live-tools/blob/731487601e06f8d598d1db03c924b58a87a80491/conf/user.conf#L24

好的  谢谢大哥

**Comment by yawwwwwn** [comment]
> 然后因为conf 没开定时 所以没跑 schedule.run() 没机会置回false

抱歉，没考虑到这个，已修复 [#ed20499](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/ed20499437c625f6aecd8d8a007c07d01f07d46c)。

**Comment by yawwwwwn** [comment]
不是说一个人只能开一个 issue 啊。我之前没关这个因为还有大佬自己分享的备用舰长服务器等有用信息。出了新的问题就新开 issue。改之前 issue 的名字什么，不同问题杂糅在一起，太乱了，所以这个关了吧。

**Comment by a-writer** [comment]
好的抱歉...没怎么用过github

**Comment by yawwwwwn** [comment]
> 好的抱歉...没怎么用过github

没事。
