### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by valetzx** [Dawnnnnnn/bilibili-live-tools#279]
![20200305113046](https://user-images.githubusercontent.com/45054400/75945320-d0f4c000-5ed4-11ea-87cd-33e3619deafa.png)
 这里是一只小白，求解这报错

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/75946207-6d1fc680-5ed7-11ea-8edb-5db36ae7742b.png)

**Comment by Billyzou0741326** [comment]
`python3 -m pip install -r requirements.txt`
`python3 main.py`

**Comment by valetzx** [comment]
好谢谢我试试

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/75947092-21225100-5eda-11ea-988e-c629f165bd4f.png)
no ou'toutput

**Comment by Billyzou0741326** [comment]
`python3 main.py`

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/75947552-b7a34200-5edb-11ea-8032-64a3a6fde8cc.png)
thanks

**Comment by yawwwwwn** [comment]
本项目要求 python 版本至少 3.6，你之前 `invalid syntax` 因为使用的是 python 2.7。
