### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by Mabisi** [Dawnnnnnn/bilibili-live-tools#282]
这个脚本运行后是24小时运行吗？开启后就不用管了
还是每天需要运行一次？

**Comment by Mabisi** [comment]
![image](https://user-images.githubusercontent.com/19968269/76189206-14249b00-6215-11ea-8592-95839294020b.png)
新问题,卡在这里半天了 没反应。

**Comment by Billyzou0741326** [comment]
`python main.py`

**Comment by Mabisi** [comment]
> `python main.py`

![image](https://user-images.githubusercontent.com/19968269/76189505-da07c900-6215-11ea-874f-b8c6a33ed3f9.png)
 一样卡在这里..

**Comment by Billyzou0741326** [comment]
刚测了下我这边没问题（Powershell）

可以试试
- 清一下cookies
- 确保运行后不要点cmd界面内

**Comment by Mabisi** [comment]
> 刚测了下我这边没问题（Powershell）
> 
> 可以试试
> 
> * 清一下cookies
> * 确保运行后不要点cmd界面内

谢谢了，打包成EXE跑起来了
