### ISSUE TITLE
请问这个是什么问题啊

### ISSUE THREAD

**Issue by zengkuankuan** [Dawnnnnnn/bilibili-live-tools#284]
我的大航海都是这样的
[2020-03-17 23:42:12] 确认获取到大航海抽奖 2210512
[2020-03-17 23:42:12] check_results:
# <class 'tasks.guard_raffle_handler.GuardRafflJoinTask'>
# [(-2, (0, 240), 757349, 2210512)]

**Comment by yawwwwwn** [comment]
我怀疑你这是 bili2.0，建议直接移步 [👉](https://github.com/yjqiang/bili2.0/issues)。

**Comment by yjqiang** [comment]
我写的调试逻辑，正常
