### ISSUE TITLE
广播抽奖参与概率

### ISSUE THREAD

**Issue by blackzero-a** [Dawnnnnnn/bilibili-live-tools#286]
本次推送广播抽奖次数:169 
本次参与广播抽奖次数:39 

概率略低
可以调节吗

**Comment by yawwwwwn** [comment]
这不是参与概率低。因为多分区监控下全站推送每个分区都有，所以推送数量大于参与是正常的。本项目全抽，没有设置抽奖参与概率，隔壁 [bili2.0](https://github.com/yjqiang/bili2.0) 有，需要调低概率的去了解一下。

**Comment by xia-i** [comment]
调低概率没有意义，该进黑屋还是进

**Comment by yjqiang** [comment]
你搁这儿祸水东引呢

**Comment by yawwwwwn** [comment]
![9E%E{4EIULYPID8T2 6C``H](https://user-images.githubusercontent.com/40122222/77817513-be099000-710e-11ea-8c9c-efd05e3bbf4a.jpg)
:ok_hand:

**Comment by Dawnnnnnn** [comment]
本项目无丢弃抽奖功能，收到什么推送就参加什么抽奖
