### ISSUE TITLE
请问当前docker版里面的bilibili-live-tools是最新版本吗？

### ISSUE THREAD

**Issue by DeSireFire** [Dawnnnnnn/bilibili-live-tools#288]
如题，为了方便管理多个账号的定时开关，我一直在使用的是docker版..
但是我感觉我似乎一直在使用的是旧版本的bilibili-live-tools，
重新下了一次docker镜像似乎也没有更新的亚子..
如果docker镜像上是旧版bilibili-live-tools，那最近有更新计划吗？

**Comment by Dawnnnnnn** [comment]
为啥你认为是旧版的呢，docker那个新建container的时候不是会git clone吗
