### ISSUE TITLE
关于平台兼容问题

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#29]
https://github.com/yjqiang/bilibili-live-tools/issues/4
这里面的rgb显示方式不同平台支持不一样，比如我用的ios pythonista是console.set_color()，但是其他的平台是print(“0m”)（类似的，忘记了。。。），但是ios平台可以随意设置rgb，而其余平台只能指定有限10个颜色左右。
怎么处理不同平台问题？

**Comment by yjqiang** [comment]
我想的办法是import那里用try语句load不同包
执行那里利用platform判断执行不同语句

坏处：呃就是复杂了一些

**Comment by yjqiang** [comment]
我现在自己的分支上做掉，希望可以合并到你这里

**Comment by Dawnnnnnn** [comment]
好的，感谢PR。

**Comment by Dawnnnnnn** [comment]
我先解决掉服务器重连的问题。。

**Comment by Dawnnnnnn** [comment]
已设置直接push的权限，你可以直接push上来了

**Comment by yjqiang** [comment]
ok
