### ISSUE TITLE
首先先给大佬点赞，然后有1个建议和1个疑问

### ISSUE THREAD

**Issue by L-jasmine** [Dawnnnnnn/bilibili-live-tools#290]
1.希望能通过命令指定配置文件，因为有时候会开多个（自己一个，帮小妹妹挂一个），按目前的操作，就得cp一份。
2.能不能有办法解决登陆过程中需要验证时导致失败的问题？

**Comment by yawwwwwn** [comment]
1. 个人有非常简陋的只需要复制 bili.conf 的版本，但是实现得太丑陋所以算了。支持多用户得重构。
2. 你是说目前的字符识别验证码，弹出图片手动输入这一过程有问题吗？发 log 看看。

**Comment by Dawnnnnnn** [comment]
没删cookie信息

**Comment by Dawnnnnnn** [comment]
1、不支持多用户
2、验证码修了修，大概修复了
