### ISSUE TITLE
Mirror Bilibili Usage 哔哩哔哩镜像网站

### ISSUE THREAD

**Issue by orionHong** [Dawnnnnnn/bilibili-live-tools#292]
我注意到login代码在获取access token的时候用的是一个镜像网站，这里有什么原因不用主站吗？以及这个镜像是从哪里获取的？

>  url = "https://passport.snm0516.aisee.tv/api/captcha?token=5598158bcd8511e1"

https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/login.py#L33

我在做一个project，所以想确定是安全的

谢谢🙏

**Comment by yawwwwwn** [comment]
#249
