### ISSUE TITLE
HTTP 412 错误 – 先决条件失败 (Precondition failed) 

### ISSUE THREAD

**Issue by ThreeCatsLoveFish** [Dawnnnnnn/bilibili-live-tools#297]
今天14：00左右，有一场PK神仙打架，一共送了大约1000小电视，出现了系统繁忙，导致所有脚本出现412错误，此前完全正常，请问有什么解决方案吗？
![TIM图片20200429142925](https://user-images.githubusercontent.com/44898640/80566718-2f967000-8a26-11ea-8e69-cbb423543885.png)

**Comment by witrian** [comment]
这里也一样，而且手机端直接进直播间就 412了。 不过我这是海外用户

**Comment by shoucandanghehe** [comment]
短时间请求数过多，B站风控

**Comment by ThreeCatsLoveFish** [comment]
应该是b站的问题，我的服务器在北京，之前从来没有任何问题，今天下午两点太疯狂了，直接送了大概60万RMB的东西，太猛了

**Comment by 666saltedfish** [comment]
可以换网或者等一会儿就好了

**Comment by shoucandanghehe** [comment]
工会斗法，一般送多少反多少
换个IP就行

**Comment by witrian** [comment]
我这里恢复正常了

**Comment by ThreeCatsLoveFish** [comment]
我的服务器上挂了四个号可能太多了，现在也没好

**Comment by ThreeCatsLoveFish** [comment]
OK解决了，感谢大家
