### ISSUE TITLE
建议：将配置文件加入gitignore

### ISSUE THREAD

**Issue by paradox8599** [Dawnnnnnn/bilibili-live-tools#298]
当前配置文件和项目版本绑定，每次更新都需要手动修改配置文件

建议将程序读取的配置文件列入gitignore，另外创建配置文件示例加入git

.gitignore
```gitignore
conf/user.conf
conf/bilibili.conf

或者

conf/*.conf
```

新文件：
```
conf/user.conf.example
conf/bilibili.conf.example
```

**Comment by CanvasQAQ** [comment]
同意，这样docker也能挂载外部配置文件使用了

**Comment by CanvasQAQ** [comment]
啊docker这边没事了，刚刚测试了，将自己的user.conf文件挂载为docker的/app/conf/user.conf 是会替换掉原有配置的，所以启动容器的时候进行挂载就行了 ，已经尝试成功

**Comment by Dawnnnnnn** [comment]
可以，但我懒了，最近项目大概会archive，凑合用吧。。
