### ISSUE TITLE
可以成功登录，但是会出现错误

### ISSUE THREAD

**Issue by GOOD-AN** [Dawnnnnnn/bilibili-live-tools#299]
出现以下错误提示：
<412 Precondition Failed>，60s后重试

**Comment by GOOD-AN** [comment]
好似像ip封禁，用家里wifi无法正常进入直播间，电脑端只有直播画面，手机端直接412错误，切换到手机移动数据上恢复正常。

**Comment by Sistercon** [comment]
412是ip被风控了

**Comment by ThreeCatsLoveFish** [comment]
我也风控了，就刚刚

**Comment by Hitiko** [comment]
不久前有一个房间号有人送出了700个小电视
你极有可能是因为这700个小电视的频繁领取而被412了

**Comment by henut** [comment]
emmmm这过段时间就能好嘛

**Comment by ThreeCatsLoveFish** [comment]
对的很快的，大概半小时

**Comment by GOOD-AN** [comment]
已恢复正常，感谢！
