### ISSUE TITLE
使用config配置文件

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#30]
debug字段可以方便我们调试
后续的platform可以直接自己改
简单api的修改可以丢到这里面
选择运行任务可以扔到里面（本次是想读取弹幕还是挂件抽奖）
bilibili文件的一部分可以丢过来
如果是后面挂代理也可以丢配置过来

**Comment by yjqiang** [comment]
感觉自己正在把坑越挖越大。。。

**Comment by handsomebubu** [comment]
观2位大佬讨论技术
