### ISSUE TITLE
功能性建议

### ISSUE THREAD

**Issue by Hitiko** [Dawnnnnnn/bilibili-live-tools#300]
就在不久前，有一个房间有好几个人总共送出了700个小电视，而导致一些脚本用户因此被412
据悉，这个房间曾在不久前也出现过类似的情况
建议功能：

1. 出黑名单功能，方便对指定房间做黑名单处理
2. 一个房间出现大量小电视等 的时候不领取

**Comment by shoucandanghehe** [comment]
理论上只要限制每秒请求数就行
小电视是180s（好像是）
而B站限制在每秒十几个请求左右
限制每秒16请求可以保证4个号全领700小电视
而理论上也不会触发B站请求限制

**Comment by Hitiko** [comment]
> 理论上只要限制每秒请求数就行
> 小电视是180s（好像是）
> 而B站限制在每秒十几个请求左右
> 限制每秒16请求可以保证4个号全领700小电视
> 而理论上也不会触发B站请求限制

可以是可以，但是我觉得比起领干净那么大量的小电视，不领的操作更好点

**Comment by 2314933036** [comment]
> > 理论上只要限制每秒请求数就行
> > 小电视是180s（好像是）
> > 而B站限制在每秒十几个请求左右
> > 限制每秒16请求可以保证4个号全领700小电视
> > 而理论上也不会触发B站请求限制
> 
> 可以是可以，但是我觉得比起领干净那么大量的小电视，不领的操作更好点

我觉得还是限制请求频率好点.
量大412应该在帐号较多的情况下才发生,对于只挂了一个,两个号的没有必要不领(到嘴的肉干嘛不吃

**Comment by yawwwwwn** [comment]
我全都要.jpg
现在没小电视了，问题解决，关了。
