### ISSUE TITLE
长时间运行下 领取不了瓜子宝箱和双端观看任务

### ISSUE THREAD

**Issue by henut** [Dawnnnnnn/bilibili-live-tools#302]
用久了 好像会领取不了瓜子宝箱和双端观看任务
但是重新下文档，再登录又会解决..

**Comment by Myer921** [comment]
补充，在清理 bilibili.conf 中的 [saved-session] 值信息后，让脚本重新获取信息可以解决这个问题
在一部分的日志查看中，表现为：银瓜子兑换硬币提示请登录

**Comment by yawwwwwn** [comment]
懂了，银瓜子兑换硬币和开宝箱都是用的 App 端 access_token，感觉是 token 会比 cookie 先过期？因为我们是在心跳中循环检查 cookie 的可用性来重新登录的。出来修 bug @Dawnnnnnn 。

**Comment by Myer921** [comment]
好奇，应援团/兑换硬币瓜子/每日银瓜子领取都是走 APP 的 api 嘛？

**Comment by yawwwwwn** [comment]
> 好奇，应援团/兑换硬币瓜子/每日银瓜子领取都是走 APP 的 api 嘛？

都是。现在了解的情况，据说是 PC 端 cookie 有效期改成几个月了，token 还是每个月过期。

**Comment by sdnian** [comment]
出现这个问题，是把 [saved-session] 整个删除，再重新执行吗?
