### ISSUE TITLE
脚本接收到不完整的推送后会卡死

### ISSUE THREAD

**Issue by andywang425** [Dawnnnnnn/bilibili-live-tools#304]
> [2020-05-11 00:00:21] [Error]   Failed when parsing: {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2478400, "RoomId": 71043, "MasterName": "\u732b\u5927\u53ef", "MasterId": 139905, "Sender": "\u4e91\u79c3
 Traceback (most recent call last):
  File` "/usr/local/bin/bilibili-live-tools-master/TCP_monitor.py", line 119, in ReadSocketData
    json_data = json.loads(body)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 1 column 155 (char 154)

几次遇到这种情况，一旦接收到错误的推送信息脚本就不工作了。只好重启下脚本。

**Comment by Dawnnnnnn** [comment]
更新了吗

**Comment by andywang425** [comment]
哦哦原来昨天更新了，对不起没注意到
