### ISSUE TITLE
本次更新后，我在群辉 docker上的 更新失败，已尝试重新安装等 无法解决

### ISSUE THREAD

**Issue by BlueskyClouds** [Dawnnnnnn/bilibili-live-tools#308]
![TIM截图20200516125258](https://user-images.githubusercontent.com/39831773/82110986-671a5180-9774-11ea-8c1a-72ed0aa3bac4.png)

**Comment by BlueskyClouds** [comment]
看了一遍  貌似没看懂，谁知道怎么解决了！

**Comment by Dawnnnnnn** [comment]
docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools

**Comment by CanvasQAQ** [comment]
> 看了一遍 貌似没看懂，谁知道怎么解决了！
你这个是上次更新之后没有更新新的docker镜像，换了就好
