### ISSUE TITLE
舰长亲密度

### ISSUE THREAD

**Issue by lyf1134** [Dawnnnnnn/bilibili-live-tools#310]
最近我的舰长亲密度好像变成了当天的辣条了
比如说11点领的12点就过期了
而且30天有效期的每天只有2、300
感觉每天都要扔掉几千

**Comment by witrian** [comment]
从前天就是这样了 舰长都会领成 当天辣条
如果不想浪费的话，你可能要改一下代码/或者要过期前重启一下，
然后让程序跑那个自动送过期礼物(要设置conf)。

**Comment by yawwwwwn** [comment]
自动送礼这块我们一直没好好写，很抱歉。
不过现在没舰队辣条了，问题解决，关了。
