### ISSUE TITLE
自动送礼功能

### ISSUE THREAD

**Issue by sdnian** [Dawnnnnnn/bilibili-live-tools#311]
现在辣条多数一天就过期，自动送礼功能可不可以调整成，每日晚上 12 点之前，把到期的辣条送出去？
另外房间可不可以指定多个？依序送出辣条，达到上限的就下一个房间，直到所有指定的房间都达本日上限，或者今日到期的辣条送完了为止。

**Comment by suica-me** [comment]
可以配合 https://github.com/yjqiang/bili2.0 此脚本一起食用
