### ISSUE TITLE
DockerFile 强制使用python3

### ISSUE THREAD

**Issue by Snowflake-Pink** [Dawnnnnnn/bilibili-live-tools#317]
https://github.com/Dawnnnnnn/bilibili-live-tools/blob/0cb4ac749845a6b8fa3fa8bca7d9647d57c1d2c9/Dockerfile#L21

由于个人原因，默认python版本设为3总是有奇奇怪怪的错误（在其他地方上，非此项目），如果已是预期行为，勿喷

**Comment by Dawnnnnnn** [comment]
emmm，不是很懂
既然用了Docker，pyhton就是Docker里的python环境了，不应该影响别的容器啊。。
