### ISSUE TITLE
登录接口报错Exception: {"code":-400,"message":"","ts":1593267547}

### ISSUE THREAD

**Issue by qianghuohhh** [Dawnnnnnn/bilibili-live-tools#318]
登录接口报错Exception: {"code":-400,"message":"","ts":1593267547}，昨天还正常的，不知道是不是我自己的问题
接口是https://passport.snm0516.aisee.tv/api/tv/login
我又尝试使用了接口https://passport.bilibili.com/api/v3/oauth2/login
电脑上正常，服务器上会报一个缺验证码的错
希望大佬能帮我看下，困扰一天了

**Comment by yawwwwwn** [comment]
`"code":-400` 这个没见过。
v3 接口我刚才出验证码，给的是点选，但我尝试用本项目内的打码逻辑成功登陆了。其实应该直接重试就有概率不出验证码。
