### ISSUE TITLE
有账号可以领取辣条，却一直提示‘连接无法建立，请检查本地网络’

### ISSUE THREAD

**Issue by ishkong** [Dawnnnnnn/bilibili-live-tools#320]
树莓派4B
Centos7 ARM
Python 3.8.1
同时挂4个号，其中3个全部正常，但有1个一直提示‘连接无法建立，请检查本地网络状况’
4个号都可以领取辣条
请问那个有问题的是账号问题吗？

**Comment by yawwwwwn** [comment]
“连接无法建立，请检查本地网络状况”是连接弹幕服务器出错，与账号无关。我们也没带账号信息去连服务器。这个应该是当时B站服务器调整或本地网络问题。
