### ISSUE TITLE
直播宝箱

### ISSUE THREAD

**Issue by ThreeCatsLoveFish** [Dawnnnnnn/bilibili-live-tools#321]
貌似直播宝箱不行了？昨天还是好的，但是今天手机端观看和宝箱都没有了
![图片](https://user-images.githubusercontent.com/44898640/86194369-e5924d80-bb80-11ea-9cab-a39f3fd16818.png)
图上的是我今天自己领取的

**Comment by ThreeCatsLoveFish** [comment]
我记得今天b站直播要改，下午ios和安卓的金瓜子会通用，会不会和这个有关系

**Comment by xia-i** [comment]
你可以尝试重新登录账号看一下，可能是token到期

**Comment by ThreeCatsLoveFish** [comment]
我删了accesskey重新登录了一下就好了，谢谢大佬
所以这个脚本是没有refreshkey的是吗？

**Comment by Billyzou0741326** [comment]
倒不是没有 只是token过期比cookies早 所以其它用到cookies的功能没影响

**Comment by ThreeCatsLoveFish** [comment]
哦哦怪不得舰长没有问题 了解了
