### ISSUE TITLE
检测到房间有抽奖，但不能参与领奖

### ISSUE THREAD

**Issue by DJY520** [Dawnnnnnn/bilibili-live-tools#325]
检测到房间有抽奖，但不能参与领奖，是不是B站修改了啥东西导致不能参与领奖

**Comment by yawwwwwn** [comment]
现在大部分高能都没有抽奖了。可以去翻翻破绽站直播区公告。广播抽奖一天就剩一百来辣条吧。

提前说一下，不要在本项目里讨论~破绽策划有没有妈~的问题，希望大家更多地在技术层面讨论。

**Comment by HIjack2015** [comment]
![image](https://user-images.githubusercontent.com/10767193/88517661-ca9ce700-d021-11ea-9dba-ff5f1837aca8.png)
是这个公告导致的吧,那可真让人难受

**Comment by nemosun** [comment]
> ![image](https://user-images.githubusercontent.com/10767193/88517661-ca9ce700-d021-11ea-9dba-ff5f1837aca8.png)
> 是这个公告导致的吧,那可真让人难受
这个公告在哪看的，就看到过说是开通舰长直升21级粉丝牌，我tm，新策划孤儿石锤

**Comment by YOYO-beta** [comment]
是我食用方法不对吗？我勋章里有主播在直播的啊，为什么挂机挂不到小心心？

**Comment by Dawnnnnnn** [comment]
> 是我食用方法不对吗？我勋章里有主播在直播的啊，为什么挂机挂不到小心心？

#324
