### ISSUE TITLE
直播间切换过于频繁，以及希望提供弹幕抽奖开关

### ISSUE THREAD

**Issue by OrdosX** [Dawnnnnnn/bilibili-live-tools#332]
## 问题描述
查看直播观看历史记录的时候，发现观看直播间的切换频率非常高，基本上每分钟都会换好几个，严重影响了对真正观看历史的查找，附上截图如下：
![截图](https://user-images.githubusercontent.com/26003092/90335113-dd914e80-e004-11ea-8baf-c279f74f8603.png)

## 诉求
* 希望能够修复这个问题
* 希望能够增加一个关闭弹幕抽奖监听的选项，可以单纯的挂机拿小心心

## 运行环境
* 本体版本为截至目前最新的提交31b1f0a
* Python版本3.7.3
* 系统为Raspbian 10

**Comment by CberYellowstone** [comment]
历史记录应该关不掉..
关闭监听可以应该可以直接吧配置文件里面的服务器删了

**Comment by OrdosX** [comment]
删除整个`[monitoy_server]`节后报错`KeyError`无法运行，将该节下`on/off`项改成0后仍然会监听弹幕抽奖，似乎不是这个在控制的。

尝试注释掉`Rafflehandler`及其引用，虽然仍然会出现检测到抽奖的log，但是不会实际参与，也就不会出现在播放历史里，问题初步解决，仍在探索其他解决方案

**Comment by yawwwwwn** [comment]
改了一下抽奖的程序，不会再有这么多观看记录的提交了。（[#7acc569](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/7acc569dd4710792e7c996c3b735440b222b7033)）
提交观看记录是为了模拟真实进房间抽奖，给不进黑屋提供一个心理上的保障。
如果实在一条都不想看到，可以自己注释掉[这一行](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/7acc569dd4710792e7c996c3b735440b222b7033/bilibiliCilent.py#L54)，加开关太麻烦了，鸽置。
