### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by GOOD-AN** [Dawnnnnnn/bilibili-live-tools#335]
报错提示：连接无法建立，请检查本地网络状况,2s后重连
![批注 2020-08-28 165135](https://user-images.githubusercontent.com/53306377/91541873-933a9680-e94f-11ea-880b-4b26a39fdf79.png)

**Comment by dskaowu** [comment]
+1
最近几天经常出现

**Comment by MejiroRina** [comment]
把 bilibili.conf 里面的 monitor_server 关掉就行了

**Comment by GOOD-AN** [comment]
> 把 bilibili.conf 里面的 monitor_server 关掉就行了

哦。。。把监控服务器忘了，感谢，我回去试试
