### ISSUE TITLE
问题，重新开一个lssuse

### ISSUE THREAD

**Issue by emmmmmmmmmmmmmmmmm** [Dawnnnnnn/bilibili-live-tools#37]
添加后错误代码又变了
Traceback (most recent call last):
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\login.py", line 42, in success
    response = requests.post(url, data=payload, headers=headersprint(response.json()))
NameError: name 'headersprint' is not defined

**Comment by Dawnnnnnn** [comment]
。。。。这样写

        response = requests.post(url, data=payload, headers=headers)
        print(response.json())

**Comment by emmmmmmmmmmmmmmmmm** [comment]
{'ts': 1522151457, 'message': 'CAPTCHA is not match', 'code': -105}
Traceback (most recent call last):
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\login.py", line 44, in success
    access_key = response.json()['data']['token_info']['access_token']
KeyError: 'data'

**Comment by Dawnnnnnn** [comment]
噢，出验证码了，应该是异地登陆太多了

**Comment by emmmmmmmmmmmmmmmmm** [comment]
前面出现的错误就是因为异地登陆太多了？

**Comment by yjqiang** [comment]
console问题已经修复

**Comment by yjqiang** [comment]
你是挂在vps上么

**Comment by emmmmmmmmmmmmmmmmm** [comment]
没，校园网，今天突然强制要用客户端登，以前直接在网页登陆的
