### ISSUE TITLE
支持，然而可以把抽奖奖励显示出来保存到本地吗

### ISSUE THREAD

**Issue by X-TY** [Dawnnnnnn/bilibili-live-tools#4]
什么鬼

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Administrator\Desktop\bilibili-live-tools-master\applogin.py 
 Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bilibili-live-tools-master\applogin.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
>>>

**Comment by X-TY** [comment]
什么鬼

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Administrator\Desktop\bilibili-live-tools-master\applogin.py 
 Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bilibili-live-tools-master\applogin.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
>>>

**Comment by Dawnnnnnn** [comment]
可以自己加个写入文件的功能啊，两三行代码就解决了

**Comment by Dawnnnnnn** [comment]
@X-TY accesskey 目前可以通过项目中的那个登陆文件获得

**Comment by Dawnnnnnn** [comment]
@X-TY 报错是因为没有还没有安装模块....百度一下报错信息就ok

**Comment by X-TY** [comment]
emmm，问题这个模块…… 安装最麻烦

**Comment by Dawnnnnnn** [comment]
@X-TY (｀・ω・´)是有点麻烦，不过处理一次问题以后就有经验了

**Comment by X-TY** [comment]
Crypto 还是 pycrypto
