### ISSUE TITLE
安卓pydroid3

### ISSUE THREAD

**Issue by jjnnnh** [Dawnnnnnn/bilibili-live-tools#42]
apk下载链接: https://pan.baidu.com/s/1zUxGxekXUD1COJ713qpu7A 密码: 1r4w
安装[README.md](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/README.md)要求第三方库
![pip](https://user-images.githubusercontent.com/37836145/37968005-91e744cc-31ff-11e8-9cfd-9f790ccd95fa.gif)
下载https://github.com/Dawnnnnnn/bilibili-live-tools/releases 的Source code (zip)
下载后全部解压
运行
![default](https://user-images.githubusercontent.com/37836145/37968076-c77622ca-31ff-11e8-87e1-e83bde3526fc.gif)

**Comment by yjqiang** [comment]
正常使用么？

**Comment by jjnnnh** [comment]
正常使用

**Comment by yjqiang** [comment]
如果觉得很好的话，你提交一下pull request吧，可以现在只改readme，后续可以考虑增加pydriod特殊支持

**Comment by yjqiang** [comment]
@Dawnnnnnn  我是不是无意间又开了一个坑。。。

**Comment by Dawnnnnnn** [comment]
你把手机使用的大门打开了 = =。。

**Comment by jjnnnh** [comment]
手机运行截图![mi_20180327_205645](https://user-images.githubusercontent.com/37836145/37968741-85be09d6-3201-11e8-99fb-a09b9a9e5ed7.png)

**Comment by yjqiang** [comment]
@Dawnnnnnn  你有安卓设备吗 你负责这个坑？

**Comment by Dawnnnnnn** [comment]
还需要干啥，在安卓上加颜色吗

**Comment by yjqiang** [comment]
后续所有的支持，如果有必要的话。。。

**Comment by Dawnnnnnn** [comment]
这个到时候看还需要干啥吧，目前来看还是正常运行的= =

**Comment by emmmmmmmmmmmmmmmmm** [comment]
能不能把pydroid APP共享出来

**Comment by jjnnnh** [comment]
不能apk发到这里，自行百度

**Comment by Dawnnnnnn** [comment]
@yjqiang 
我们群内交流一波吧，我已经看不懂你写的弹幕颜色模块了
![image](https://user-images.githubusercontent.com/24506421/37969767-2db495e0-3204-11e8-893e-eb348a1e88bb.png)

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![Uploading Screenshot_2018-03-27-21-15-47-266_ru.iiec.pydroi.png…]()

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![screenshot_2018-03-27-21-15-47-266_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37969952-b94da3a8-3204-11e8-8eed-da2ecb1e5346.png)

**Comment by jjnnnh** [comment]
还有release中的exe版本只能64位系统能用，我自己弄32位系统能用exe

**Comment by Dawnnnnnn** [comment]
emmm，因为我是在64位环境下打包的

**Comment by jjnnnh** [comment]
----------bilibili live tools 编译exe脚本-----------
python环境 : [MSC v.1900 32 bit (Intel)]
python32环境编译32位exe，python64环境编译64位exe
****************检查安装第三方库开始******************
Requirement already satisfied: pyinstaller in c:\python36-32\lib\site-packages
Requirement already satisfied: setuptools in c:\python36-32\lib\site-packages (from pyinstaller)
Requirement already satisfied: pefile>=2017.8.1 in c:\python36-32\lib\site-packages (from pyinstaller)
Requirement already satisfied: macholib>=1.8 in c:\python36-32\lib\site-packages (from pyinstaller)
Requirement already satisfied: future in c:\python36-32\lib\site-packages (from pyinstaller)
Requirement already satisfied: altgraph>=0.15 in c:\python36-32\lib\site-packages (from macholib>=1.8->pyinstaller)
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
****************检查安装第三方库结束******************
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\LICENSE
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\README.md
141 INFO: PyInstaller: 3.3.1
141 INFO: Python: 3.6.4
141 INFO: Platform: Windows-10-10.0.14393-SP0
141 INFO: wrote C:\Users\GJtest\Desktop\bilibili-live-tools\run.spec
141 INFO: UPX is not available.
141 INFO: Extending PYTHONPATH with paths
['C:\\Users\\GJtest\\Desktop\\bilibili-live-tools',
 'C:\\Users\\GJtest\\Desktop\\bilibili-live-tools']
141 INFO: checking Analysis
141 INFO: Building Analysis because out00-Analysis.toc is non existent
141 INFO: Initializing module dependency graph...
141 INFO: Initializing module graph hooks...
156 INFO: Analyzing base_library.zip ...
7706 INFO: running Analysis out00-Analysis.toc
                                                                          13579 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python36-32\python.exe
13908 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\python36-32\python36.dll
13955 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\python36-32\python36.dll
15036 INFO: Caching module hooks...
15052 INFO: Analyzing C:\Users\GJtest\Desktop\bilibili-live-tools\run.py
15350 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
20910 INFO: Loading module hooks...
20910 INFO: Loading module hook "hook-certifi.py"...
20910 INFO: Loading module hook "hook-encodings.py"...
21083 INFO: Loading module hook "hook-pydoc.py"...
21083 INFO: Loading module hook "hook-requests.py"...
21083 INFO: Loading module hook "hook-xml.py"...
21286 INFO: Looking for ctypes DLLs
21318 INFO: Analyzing run-time hooks ...
21333 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
21348 INFO: Looking for dynamic libraries
21458 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\python36-32\DLLs\_ssl.pyd
21583 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\python36-32\DLLs\_hashlib.pyd
21803 INFO: Looking for eggs
21803 INFO: Using Python library c:\python36-32\python36.dll
21818 INFO: Found binding redirects:
[]
21834 INFO: Warnings written to C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\warnrun.txt
22054 INFO: Graph cross-reference written to C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\xref-run.html
22085 INFO: checking PYZ
22085 INFO: Building PYZ because out00-PYZ.toc is non existent
22085 INFO: Building PYZ (ZlibArchive) C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PYZ.pyz
24027 INFO: Building PYZ (ZlibArchive) C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PYZ.pyz completed successfully.
26267 INFO: checking PKG
26267 INFO: Building PKG because out00-PKG.toc is non existent
26267 INFO: Building PKG (CArchive) out00-PKG.pkg
29007 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
29024 INFO: Bootloader c:\python36-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
29024 INFO: checking EXE
29039 INFO: Building EXE because out00-EXE.toc is non existent
29039 INFO: Building EXE from out00-EXE.toc
29039 INFO: Appending archive to EXE C:\Users\GJtest\Desktop\bilibili-live-tools\dist\run.exe
29039 INFO: Building EXE from out00-EXE.toc completed successfully.
拒绝访问。
移动了         0 个文件。
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\run.spec
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\dist\run-32bit.exe
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\base_library.zip
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-Analysis.toc
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-EXE.toc
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PKG.pkg
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PKG.toc
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PYZ.pyz
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\out00-PYZ.toc
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\run.exe.manifest
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\warnrun.txt
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\build\run\xref-run.html
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\__pycache__\run.cpython-36.pyc
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\API.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\bilibili.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\bilibiliCilent.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\bit.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\login.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\LotteryResult.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\OnlineHeart.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\run.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\Silver.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\storm.py
删除文件 - C:\Users\GJtest\Desktop\bilibili-live-tools\Tasks.py
目录不是空的。
编译完成,已打开32位exe测试运行,请按任意键退出.

**Comment by jjnnnh** [comment]
@echo off & TITLE 编译 bilibili-live-tools exe
echo ----------bilibili live tools 编译exe脚本-----------
python bit.py
echo python32环境编译32位exe，python64环境编译64位exe
echo ****************检查安装第三方库开始******************
pip install pyinstaller
echo ****************检查安装第三方库结束******************
del /F /S /Q "%~dp0LICENSE" 
del /F /S /Q "%~dp0README.md"
pyinstaller -F run.py
RENAME %~dp0\dist\run.exe run-32bit.exe
move /Y %~dp0\dist\run-32bit.exe %~dp0
del /F /S /Q "%~dp0\run.spec" "%~dp0dist" "%~dp0build" "%~dp0__pycache__" "*.py"
rmdir "%~dp0dist"
rmdir "%~dp0build\run"
rmdir "%~dp0build"
rmdir "%~dp0\%input%\__pycache__"
start %~dp0\run-32bit.exe
echo 编译完成,已打开exe测试运行,请按任意键退出.
@Pause>nul
exit

bit.py
#!/usr/bin/env python    
#coding=utf-8  
  
#platform_mode.py  
  
import platform
  
#global var  
#是否显示日志信息  
SHOW_LOG = True 
  
def get_python_compiler():  
    '''''Returns a string identifying the compiler used for compiling Python'''  
    return platform.python_compiler()   
  
def show_python_all_info():  
    print('python环境 : [{}]'.format(get_python_compiler()))   
  
def show_python_info():  
    '''''只打印python的信息，没有解释部分'''  
    print(get_python_compiler())   
        
def test(): 
    if SHOW_LOG:  
        show_python_all_info()  
    else:  
        show_python_info()  
  
def init():  
    global SHOW_LOG  
    SHOW_LOG = True  
      
def main():  
    init()  
    test()  
  
if __name__ == '__main__':  
    main()

**Comment by emmmmmmmmmmmmmmmmm** [comment]
更新完了吗？我重新下载打开还是一样

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm 你没装第三方库

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh 如何操作？

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm 前面有安装第三方库gif图

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh 第一张图吗？安装了几次了，一开始以为漏了添加后显示已经添加

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm 安装README.md的第三方库配置的库，不用填pip install

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![Uploading Screenshot_2018-03-27-21-41-09-322_ru.iiec.pydroi.png…]()
感觉没安装成功

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![screenshot_2018-03-27-21-42-25-720_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37971256-126a39bc-3208-11e8-8925-cf5ef36343ff.png)
![screenshot_2018-03-27-21-41-09-322_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37971267-165152a4-3208-11e8-8fd5-f6d3a89ff9cd.png)
     @jjnnnh   感觉没安装成功 没填写pip install 就按照你第一张gif添加的

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm 上面LIBRARIES这些库安装好
![screenshot_2018-03-27-21-47-59-116_ru iiec pydroi](https://user-images.githubusercontent.com/37836145/37971480-a0769ae8-3208-11e8-9470-fd897ba07e16.png)

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh LIBRARIES这些库全部安装？

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh 如果是第一张gif里面的这些requests、rsa、aiohttp、webcolors，那就已经安装过了 只是运行就是那张图

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm 是的

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh  运行后就报错
![screenshot_2018-03-27-21-58-47-958_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37972087-19e702ae-320a-11e8-8087-d21a6e99470a.png)

**Comment by jjnnnh** [comment]
@emmmmmmmmmmmmmmmmm releases下载的压缩包全部解压，找到run.py运行

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh releases下载的压缩包啥意思？  我下载的压缩包全部解压在根目录，然后APP open打开run.py 就是出现上面的图

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh 
![screenshot_2018-03-27-22-08-50-516_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37972866-d93188a4-320b-11e8-937d-b295b18bf3c1.png)
![screenshot_2018-03-27-22-09-00-586_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37972869-dc188202-320b-11e8-8d14-9cd80f196451.png)

**Comment by jjnnnh** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/releases 的Source code (zip)

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![screenshot_2018-03-27-22-14-22-433_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37973071-497df386-320c-11e8-8a03-b0687c92bc93.png)
@jjnnnh  还是一样 ~

**Comment by jjnnnh** [comment]
在不行话，我丢个链接下载apk，链接: https://pan.baidu.com/s/1zUxGxekXUD1COJ713qpu7A 密码: 1r4w

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@jjnnnh 果然是APP的问题。用了你那个可以登陆了，现在测试看看 会不会自动

**Comment by emmmmmmmmmmmmmmmmm** [comment]
![screenshot_2018-03-27-23-00-46-066_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37975826-bdae065a-3212-11e8-8711-034cfc125db4.png)
@jjnnnh OJBK了，谢谢大佬~

**Comment by tt508618** [comment]
这个能不能后台运行呢？

**Comment by emmmmmmmmmmmmmmmmm** [comment]
@tt508618 比较难把不知道是不是手机问题，小米手机，不能熄屏太久，亮屏可以后台，但是APP开太多会失效

**Comment by sabersang3** [comment]
请问怎么切换帐号？

**Comment by hierarchsouth** [comment]
有iOS版的吗

**Comment by yjqiang** [comment]
> 有iOS版的吗

http://omz-software.com/pythonista/

**Comment by cjuwen** [comment]
> ![screenshot_2018-03-27-22-14-22-433_ru iiec pydroi](https://user-images.githubusercontent.com/37684328/37973071-497df386-320c-11e8-8a03-b0687c92bc93.png)
> @jjnnnh还是一样~

我也是这样，求助
