### ISSUE TITLE
没有给小白用的release版本吗（（

### ISSUE THREAD

**Issue by Naexen** [Dawnnnnnn/bilibili-live-tools#6]
不是很懂源码怎么用就是了（（

**Comment by Dawnnnnnn** [comment]
emmmmm,暂时没有,说不定后期会做图形化放到release里(flag)

**Comment by Naexen** [comment]
一定需要python 3.6吗 有没有向上兼容啊

**Comment by Dawnnnnnn** [comment]
理论上python3都是可以的....但是不兼容python2

**Comment by Naexen** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pip' is not defined

**Comment by Naexen** [comment]
>>> pip install requests
  File "<stdin>", line 1
    pip install requests
              ^
SyntaxError: invalid syntax

**Comment by Naexen** [comment]
无法理解（

**Comment by Dawnnnnnn** [comment]
我觉得你在安装python时并没有把那个pip的勾打上，你可以选择重新安装环境，或者手动将pip添加到环境变量

**Comment by Naexen** [comment]
我就直接一股脑下一步下一步了（x

**Comment by shenxihuanqi** [comment]
实物那个可以用了吗现在

**Comment by Dawnnnnnn** [comment]
实物啊。。。我还没有想到合适的方法让它避免抽到“测试抽奖”这种东西

**Comment by shenxihuanqi** [comment]
ヽ(￣ω￣(￣ω￣〃)ゝ这个难免抽到

**Comment by Dawnnnnnn** [comment]
抽到就黑号了.....比如我

**Comment by shenxihuanqi** [comment]
可以发我一份吗ヽ(￣ω￣(￣ω￣〃)ゝ我试试小号的

**Comment by Naexen** [comment]
D:\apps\python\python.exe: can't open file 'run.py': [Errno 2] No such file or directory
不知道该放在哪里（（（

**Comment by Dawnnnnnn** [comment]
emmmmmm，打开cmd，定位到run.py所在目录，然后输入 python run.py

**Comment by Dawnnnnnn** [comment]
那明天更新一下实物抽奖吧。。。。

**Comment by Naexen** [comment]
我得知道run.py在哪里啊（x

**Comment by Naexen** [comment]
是在我安装python目录里面的那个run.py么 另外是怎么定位（（x

**Comment by Naexen** [comment]
bilibili-live-tools-master
这个吧

**Comment by Dawnnnnnn** [comment]
嗯，用cmd执行cd命令,cd到那个文件夹下就行了

**Comment by Naexen** [comment]
我下载的这个没有run.py是什么情况啊（

**Comment by Naexen** [comment]
bilibili-live-tools-master这个

**Comment by Dawnnnnnn** [comment]
上截图吧

**Comment by Naexen** [comment]
我重下了一个（有了 可能是上个版本没有run.py?

**Comment by Naexen** [comment]
就六天前我建issue的时候下的

**Comment by shenxihuanqi** [comment]
谢谢大佬|･ω･｀)

**Comment by Dawnnnnnn** [comment]
昨天更新的新版本。。以前的确没有run

**Comment by Naexen** [comment]
啊好的 启动了 感谢（x
顺便明天还要更新？

**Comment by Naexen** [comment]
我连接弹幕服务器成功之后后面的都会自己运行吗0A0还是需要我自己启动啊

**Comment by Dawnnnnnn** [comment]
加个实物抽奖的东西...体验可能不怎么好

**Comment by Dawnnnnnn** [comment]
连接成功之后就不用管了

**Comment by Naexen** [comment]
好的XD感谢

**Comment by Naexen** [comment]
会有抽奖提示吗？以及奖品输出啥的

**Comment by Dawnnnnnn** [comment]
会有抽奖提示，奖品输出只会输出app端的，pc端的只会显示“加入成功”

**Comment by Naexen** [comment]
好
