### ISSUE TITLE
提醒：本软件疑似在淘宝上售卖

### ISSUE THREAD

**Issue by xuetaolu** [Dawnnnnnn/bilibili-live-tools#61]
[https://item.taobao.com/item.htm?spm=a1z10.1-c-s.w4004-18174393898.10.7bfc2196EF3YJq&id=566771848587&qq-pf-to=pcqq.group](https://item.taobao.com/item.htm?spm=a1z10.1-c-s.w4004-18174393898.10.7bfc2196EF3YJq&id=566771848587&qq-pf-to=pcqq.group)

我不清楚是否合适

**Comment by Dawnnnnnn** [comment]
emmmmmm，这件事情，借用大佬的话吧，此项目也是基于MIT协议的，我主要是为了学习。。自己写着玩的
![image](https://user-images.githubusercontent.com/24506421/38192325-f2639a0a-369e-11e8-9b4f-3ced0650079e.png)
