### ISSUE TITLE
大佬....有个问题。。

### ISSUE THREAD

**Issue by lovezm** [Dawnnnnnn/bilibili-live-tools#7]
Traceback (most recent call last):
  File "applogin.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
我pip install crypto了 还是报错...

**Comment by lovelyyoshino** [comment]
login可以不需要去掉即可，相应的功能全部分开写的

**Comment by Dawnnnnnn** [comment]
我懂了，我这就重写一个别的库的(´；ω；`)
