### ISSUE TITLE
弹幕处理模块的顽固性问题

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#83]
目前加入对reader的timeout检测，即外面包裹一层wait，如果35s（30s一次心跳，心跳包会有反馈包）超过且未读到值，那么就是超时。

reset也加入

fin的检测有个诡异的现象，fin是远程发送的，但有时手动关闭wifi会马上fin（reader在接受fin会返回长度为0的bytes），很诡异

**Comment by yjqiang** [comment]
writer检测类似

**Comment by yjqiang** [comment]
顽固问题，如果此时卡在抽奖环节，那么就会卡死不动，导致reader出现长时间不应。解决办法：session部分实现事务队列

**Comment by ihciah** [comment]
范总 你还考不考研了。。。

**Comment by Dawnnnnnn** [comment]
范总 你还考不考研了。。。

**Comment by scott90578** [comment]
范总 你还考不考研了。。。
