### ISSUE TITLE
重启弹幕未成功

### ISSUE THREAD

**Issue by emmmmmmmmmmmmmmmmm** [Dawnnnnnn/bilibili-live-tools#88]
![qq 20180418160328](https://user-images.githubusercontent.com/37684328/38919039-08d561c6-4322-11e8-8f0f-c111c25ce698.jpg)

**Comment by yjqiang** [comment]
https://stackoverflow.com/questions/17854713/error-errno-10053

**Comment by yjqiang** [comment]
怀疑是软件或系统问题，将会对这个进行暴力try pass，不确定效果
