### ISSUE TITLE
4.20release版本中出现弹幕姬异常或主动断开

### ISSUE THREAD

**Issue by sxinxins** [Dawnnnnnn/bilibili-live-tools#89]
![k0 yjvms26 dfs1b5o ier](https://user-images.githubusercontent.com/30524883/39048597-a55f3e22-44d0-11e8-9b6a-7aab876ec826.png)
今天换成4.20版本后持续出现这些信息。请问大佬是哪里出问题啦

**Comment by Dawnnnnnn** [comment]
更新一下，我暗中更换了exe，已经修了这个bug

**Comment by sxinxins** [comment]
好的，已更新，没有再出现这个问题，谢大佬。另外
![e4qeo b me5ljtgx f 91ft](https://user-images.githubusercontent.com/30524883/39050453-031962fc-44d8-11e8-86b8-765cee2cf70c.png)
实物抽奖回显没有date，运作是正常的吗？

**Comment by Dawnnnnnn** [comment]
正常，msg:"ok"就是已经参与了抽奖

**Comment by sxinxins** [comment]
哦哦 好哒
