### ISSUE TITLE
大佬，我的pi运行不了run.py，截图如下，麻烦看下

### ISSUE THREAD

**Issue by SGlace** [Dawnnnnnn/bilibili-live-tools#91]
![default](https://user-images.githubusercontent.com/22759345/40102190-6bc0c9dc-591c-11e8-9ef3-a4789fc34ee3.png)

**Comment by SGlace** [comment]
![default](https://user-images.githubusercontent.com/22759345/40151803-97b516a4-59b4-11e8-9bf9-a1df3e9dc0af.PNG)
![1](https://user-images.githubusercontent.com/22759345/40151813-a5002948-59b4-11e8-9d8a-b5ece2257d73.PNG)

**Comment by SGlace** [comment]
Python是3.6.5，依赖库五个都已经安装了，用的是树莓派

**Comment by Dawnnnnnn** [comment]
http://blog.51cto.com/13160495/2093863
那你看看这个吧。。。我也不是很懂，可能编译不完全了？

**Comment by SGlace** [comment]
感谢大佬，已解决。

`sudo apt-get install mysql-server python-mysqldb`
