### ISSUE TITLE
出现总督会停止运行

### ISSUE THREAD

**Issue by sxinxins** [Dawnnnnnn/bilibili-live-tools#93]
这两天发现一个问题。出现总督之后，不仅不会领取总督奖励，而且也不会再继续抽奖，只返回心跳。
![45 4mt49 72 f9f6 d](https://user-images.githubusercontent.com/30524883/40577189-08f3a5fc-6134-11e8-8fc5-28f904ba7bc9.png)
python和release中的exe版本都会这样。出现问题的操作系统是win server 2016
请问是因为我漏掉了什么操作吗

**Comment by Dawnnnnnn** [comment]
未知情况。。我这里还是挺正常的，重启一下吧
