### ISSUE TITLE
dalao..节奏风暴storm.py怎么用呐

### ISSUE THREAD

**Issue by wenhao801** [Dawnnnnnn/bilibili-live-tools#94]
貌似是一个抢节奏风暴的一个东西
里面其他文件也没调用storm.py
单运行就会不断输出 {'message': '', 'code': 0, 'data': [], 'msg': ''}

**Comment by Dawnnnnnn** [comment]
输出这个是正常的。。在遍历而已。。效率可以说是非常低了，仅供研究使用
